### ISSUE TITLE
Image + Link causing troubles with backspace, selection and deletion of the image

### ISSUE THREAD

**Issue by hanspagel** [ueberdosis/tiptap#1141]
leaving this here as a note, will add details later

reported by @cnicodeme

**Comment by kyng-cytro** [comment]
I'm unsure if this goes here, but how can I know when an image has been deleted? I imagined a scenario in which the image is pasted or dragged into the editor, detected by the file manager plugin, and uploaded to a server. What happens when the image is deleted? How do we manage deletions from the server?

**Comment by cnicodeme** [comment]
> I'm unsure if this goes here, but how can I know when an image has been deleted? I imagined a scenario in which the image is pasted or dragged into the editor, detected by the file manager plugin, and uploaded to a server. What happens when the image is deleted? How do we manage deletions from the server?

I'd say your server should send back the content of the editor back, with the image removed, which will be used to update the content of the editor in the frontend.
