### ISSUE TITLE
Custom view/vue component for marks

### ISSUE THREAD

**Issue by alevroub** [ueberdosis/tiptap#1152]
I've gone through the documentation and unless I've misunderstood something, there are no supported methods for custom views for marks like the 1.0 method:
```
export default class Something extends Mark {
   get view() {
      return CustomVueComponent;
   }
}
```
I've also taken a look at the `mention` extension as a guide for inline nodes but I'm still unsure how to move forward in terms of basic functionality like toggling, component state, and so on.

**Comment by yellow1912** [comment]
I wonder if this will work for link? can link be considered a node?

**Comment by iamdhrooov** [comment]
Was there a solution to this? Need to render a custom component on the Link mark. Should I create a new Node with Link features?

**Comment by justinmoon** [comment]
My application has many little notes and markdown-style links between them.

I would like to be able to show either (1) the markdown description or (2) embed the body of the linked note. I'd probably put a little button like ♻️ which user could click to toggle between the two representations.

`Link` extension already supports (1) and I've made a "node view" demo which accomplishes the latter, but if I understand correctly this thread makes it seem like I won't be able to merge these two approaches because "marks" like `Link` don't support "node views"?

Any pointers on how I might support this use case?

**Comment by martindzejky** [comment]
I wanted to add a tooltip for links to allow the user to easily change them. The way I approached this in the end was something like this:

* The link mark's `renderHTML` renders an `<a>` element with a `data-link` attribute set
* I register a new `Plugin` where I listen for the `mouseover` event
* In the event handler, I check that `event.target` is an `<a>` element with my `data-link` attribute, and then display a tooltip for it (using [Tippy.js](https://atomiks.github.io/tippyjs/))
* For the edit button in the tooltip (see below), I can retrieve the ProseMirror node for the element using `pos = view.posAtDOM(event.target)` and then `node = view.state.doc.nodeAt(pos)`

Result:

<img width="271" alt="CleanShot 2022-05-12 at 11 14 45@2x" src="https://user-images.githubusercontent.com/4700122/168036358-5184233d-55d1-46d6-adc5-c98fe3df65ff.png">
