### ISSUE TITLE
Extra new line on "return" click in iOS

### ISSUE THREAD

**Issue by nucleartux** [ueberdosis/tiptap#1214]
**Description**

**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/guide/node-views/react/#adding-a-content-editable
2. Press "Return"
4. See extra new line inside box

In Vue example extra new whole interactive box appears.

**Environment?**
 - operating system: iOS
 - browser: Safari

https://user-images.githubusercontent.com/199706/115960859-62c9ed00-a51c-11eb-9268-9120d6d098f0.mp4

https://user-images.githubusercontent.com/199706/115960873-76755380-a51c-11eb-9545-e2e2a51d4f0e.mp4

**Comment by philippkuehn** [comment]
This seems to be an issue with ProseMirror. I created an issue: https://github.com/ProseMirror/prosemirror/issues/1162

**Comment by philippkuehn** [comment]
Okay this seems to be fixed in the latest release. But there is still an issue with iOS as described here (https://github.com/ProseMirror/prosemirror/issues/1162#issuecomment-827681792): node views will be re-created when pressing enter. There has been an idea for a while to build a node view cache that could probably catch this case but for now I’m closing this.
