### ISSUE TITLE
Problems using updateAttributes when Vue component/node is not only element in document

### ISSUE THREAD

**Issue by KjetilHaaheim** [ueberdosis/tiptap#1260]
**Description**
When using a Vue component inside of editor, `editor.commands.updateAttributes` works when the component is the single item inside. When multiple items/nodes are present, `updateAttributes` cannot match `nodeType === node.type`.

**Steps to reproduce the bug**
1. Register and add custom Vue Component inside tiptap editor
2. Run updateAttributes on the custom Vue node to update component state
3. If custom component is the sole node, it works - if not, updateAttributes cannot locate the node

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
https://codesandbox.io/s/tiptap-issue-updateattributes-r66nj?file=/src/components/Tiptap.vue

**Expected behavior**
updateAttributes should find the custom node specified and update attrs. 

Please note the issue could be caused by incorrect implementation.

**Comment by philippkuehn** [comment]
Hey, you are using the `editor.commands.updateAttributes("tiptapComponent")` command wrong. This command updates a `tiptapComponent` node only if the current selection contains a `tiptapComponent` node. So adding a button which runs this code, clicking on the node to select it and then clicking on the button instead of running this in the `onCreate` hook will work.

I’m not sure what you want to achieve but there is also a `updateAttributes` method available within your node view component (it’s part of `nodeViewProps`). calling this method will always update the attributes of the current node of your component instance.

**Comment by KjetilHaaheim** [comment]
Hi @philippkuehn, thank you for your response! You are most correct, as I now see it is iterating through selected items.

What I wish to achieve, is to update attributes from outside the Vue controller - not from the component itself. Is there a better way to do this? In other words, updating props from the Vue component containing `<editor-content>`. I have tried using ref with little success.

**Comment by philippkuehn** [comment]
You can use an event bus to communicate to the vue component so it can update itself. Or you have to find the position of the node and then try to update it.

**Comment by KjetilHaaheim** [comment]
> You can use an event bus to communicate to the vue component so it can update itself. Or you have to find the position of the node and then try to update it.

Cheers! I will use event bus, I appreciate your quick response!

It would be brilliant if the content could be inserted from slot like so:
<editor-content>
  <h1>Content inside!</h1>
  <vue-component :data='localData' />
</editor-content>

Thank you for a great project! It`s such a great library, thus I have decided to sponsor it.
