### ISSUE TITLE
Strange behavior in bullet list when removing text using Delete button

### ISSUE THREAD

**Issue by zeljko-bulatovic** [ueberdosis/tiptap#1266]
**Description**
Strange behavior when deleting text using "delete" button.
**Steps to reproduce the bug**
Enter some text using numbered list that contains empty node in between. For example:
```
1. Test
  1.
    1. Test
    2. Test
2.  Test
```
Position cursor in 1. after the "Test" text. Hit delete button on your keyboard few (4-5) times. You will notice that nothing happens, and then immediately 1, 1.1 will 1.2 disappear.

**Expected behavior**
Text / nodes should be removed as button is clicked.

**Environment?**
 - operating system: OSX
 - browser: Chrome
 - tiptap versions: 
 - "@tiptap/core": "^2.0.0-beta.43",
 - "@tiptap/starter-kit": "^2.0.0-beta.39",
 - "@tiptap/vue-2": "^2.0.0-beta.22"

![Delete](https://user-images.githubusercontent.com/17200131/117122715-7257fa00-ad96-11eb-8526-f981c774d8c2.gif)

**Comment by philippkuehn** [comment]
This is intended behavior by ProseMirror and I don't want to change that. In the described situation a node selection is created. With another delete, the node will be deleted. Because of tiptap comes without styling, you don't see that node selection in tiptap by default.

https://user-images.githubusercontent.com/2500670/117125502-e051f080-ad99-11eb-9639-782840fed008.mp4
