### ISSUE TITLE
Placeholders and custom NodeViews

### ISSUE THREAD

**Issue by YousefED** [ueberdosis/tiptap#1379]
When using the placeholder plugin on elements with a custom node view, the `data-placeholder` attribute is placed on the `<div class="react-renderer">`. I think it would make more sense if it's set on the node-view-content (which can then still show a placeholder).

**Comment by philippkuehn** [comment]
I don’t think this is possible right now because rendering is done by ProseMirrors inline decorations. But I’m thinking of moving from inline decorations to widget decorations (a `<span>` element) for placeholders for some time now because using data attributes is not always ideal. But I haven’t played around with it yet.

**Comment by HeebeLee** [comment]
In addition, I think even the <p> node should be customizable, because the first line character is likely to be H1 or H2.

 please finish this idea as soon as possible, thank you.

@philippkuehn

**Comment by philippkuehn** [comment]
@HeebeLee That is already possible with the current implementation.
