### ISSUE TITLE
Wrapping an image with a link makes it clickable

### ISSUE THREAD

**Issue by RomainLanz** [ueberdosis/tiptap#1385]
Hey there! 👋 

In some of our use-case, we need to make an image clickable (wrapped in a `<a>` tag).

When we are wrapping our custom image Node inside a `<a>` tag, the tiptap renderer makes the image clickable in the editor. I have tried to disable the `Link` extension, but it is doing the same even without it.

I have made a CodeSandbox with the minimum amount of code to reproduce the issue (**using Vue 3**).
➡️  https://codesandbox.io/s/modern-architecture-1fft0?file=/src/App.vue

As you can see, when you are adding an image with a link, there is also an issue with the `Focus` extension. It does not know how to handle it properly.

I have tried different solutions to make it work, but it was not successful.
This was working fine with the previous version of tiptap.

_I am expecting the `Focus` extension to focus the Node correctly and have a non-clickable image inside the renderer._

Let me know if you need anything else!

Thanks.

**Comment by philippkuehn** [comment]
Hey, the focus extension works as expected. This is an issue with your CSS.
Add this and you’ll see the border of your selection image:

```css
a {
  display: block;
}
```

The link click is very strange because by default every link click should be prevented by ProseMirror (https://discuss.prosemirror.net/t/default-prevented-on-a-click/1160)

For the link mark extension we provide an option to make it clickable again: https://github.com/ueberdosis/tiptap/blob/3d271953c30e779a2e0287334e5fd2abea0b2325/packages/extension-link/src/link.ts#L113-L133

In your case I only found a solution by adding a plugin to prevent link clicks:


```js
import { Node } from '@tiptap/core'
import { Plugin } from 'prosemirror-state'

const Image = Node.create({

  // ...

  addProseMirrorPlugins() {
    return [
      new Plugin({
        props: {
          handleDOMEvents: {
            click: (view, event) => {
              const { pos } = view.posAtCoords({
                left: event.pageX,
                top: event.pageY,
              })
              const node = view.state.doc.nodeAt(pos)

              if (node && node.type.name === this.name) {
                event.preventDefault()
              }

              return false
            },
          }, 
        },
      })
    ]
  }
})
```

**Comment by RomainLanz** [comment]
Thanks!
