### ISSUE TITLE
Paragraph moves to the previous task list item when being deleted

### ISSUE THREAD

**Issue by amursky** [ueberdosis/tiptap#1410]
**Description**
When you remove text from a task list item, `<p>` from it moves to the previous task list item.

**Steps to reproduce the bug**
1. Remove task item text
3. Press backspace one more time
4. It's `<p>` element moves to the previous list item

**CodeSandbox**
https://codesandbox.io/s/tiptap-react-forked-4ukyn

**Expected behavior**
The `<p>` element must be deleted along with the list item.

**Screenshot, video, or GIF**
![2021-06-04 07 24 38](https://user-images.githubusercontent.com/33891482/120715872-954a0b00-c508-11eb-9cee-64a0b93f34b8.gif)

**Environment**
```
Tiptap version:
@tiptap/react: ^2.0.0-beta.45
@tiptap/starter-kit: ^2.0.0-beta.76
@tiptap/extension-task-list: ^2.0.0-beta.15
@tiptap/extension-task-item: ^2.0.0-beta.16
```

**Comment by DioNNiS** [comment]
+1

**Comment by philippkuehn** [comment]
For now task lists behaves the same as bullet lists or ordered lists so this is intended. (https://github.com/ueberdosis/tiptap/issues/118)

Maybe we will provide at some point an alternative but this is much work because we have to replace all list related commands of ProseMirror (https://github.com/ProseMirror/prosemirror-schema-list).
