### ISSUE TITLE
Empty paragraphs, getHTML() and setContent()

### ISSUE THREAD

**Issue by filt3rek** [ueberdosis/tiptap#1500]
Hej !

This is a bit linked to this issue (https://github.com/ueberdosis/tiptap/issues/412) that is already closed but that unfortunaly doesn't fit my needs :cry: 

I use tiptap2 as document editor and first I want to thanks all contributors for this awesome editor and their work.
But I have dilemma, the scenario is like that : 
- I write a document
- I save it to DB (`editor.getHTML()`)
- I use it later to send emails or display a new HTML page with this content.

When I do that with `editor.getHTML()`, empty paragraphs `<p></p>` are saved "as it", so later when I render this content, browser doesn't render empty paragraphs and all spaces done vertically this way are remove.

When now instead of using `editor.getHTML()` I do `editor.view.dom.innerHTML` to get the content and store it in DB, it stores empty paragraphs like that `<p><br></p>`, so later when I render this content via email or a new HTML page, the vertical spaces done with empty paragraphs are conserved and rendered by browser as expected.

BUT, then when I "load" this content (with `<p><br></p>`) into the editor using `editor.commands.setContent()`, the editor adds antoher `<br>` into this empty paragraph so result is `<p><br><br></p>`, and so on...

None of the solutions proposed here fit my workflow, one solution removes my vertical spaces done using empty paragraphs and another multiplies the `<br>` inside the paragraph.

Does anyone have a solution for that please ?
Maybe `setContent()` should be the exact inverse of `getHTML()` so it deals with `<p><br></p>` and doesn't add another `<br>` if there is already one inside ?

Thanks for reading,
Regards,

**Comment by philippkuehn** [comment]
I can’t and don’t want that behavior because it is how ProseMirror handles empty paragraphs. The `br` is needed to be able to click into empty paragraphs.

But you can strip empty paragraphs from your document before saving to DB or render empty paragraphs with some CSS. Something like this could help:

```css
p:empty:before {
  content: ' ';
  white-space: pre;
}
```

**Comment by filt3rek** [comment]
Philipp,

The problem is that I don't want to remove `<br>` when saving to DB because they help browser to render the content (without any `<br>` in the `<p>`, browser doesn't render the paragraph...).
I just want tiptap not to add another one `<br>` if there already is one inside the paragraph. And that is what occurs now.

**Comment by philippkuehn** [comment]
That’s why I suggested a solution to render these empty paragraphs. Or add `white-space: pre` to your wrapping element, when rendering your HTML anywhere else.

If this is a problem for you try to add `<br>` to empty paragraphs before storing your HTML und remove them before you pass it back to tiptap.

**Comment by filt3rek** [comment]
The question is : Why tiptap or prosemirror does add a `<br>` to a `<p><br></p>` (a paragraph that already has a `<br>`inside so it's already not an empty paragraph)

**Comment by joeyma22** [comment]
I'm using tiptap-markdown and there's always an extra line created below a `<p>` **if** the next element is a heading. Pretty weird. The way I solved it is by called `setContent(mainBody)` and `insertContentAt(0, thePElement)`.

**Comment by kabirjaipal-slash** [comment]
When working with `tiptap` (or similar editors), you're facing an issue where `<br>` tags with the class `ProseMirror-trailingBreak` are being added to the HTML content. This causes extra spacing when the content is passed to a PDF creator or other systems. Additionally, when fetching the HTML via `editor.view.dom.innerHTML`, these `<br>` tags are stored unnecessarily, causing formatting issues later on.

### Proposed Solution:

#### Step 1: Remove `<br>` tags with `ProseMirror-trailingBreak` class before setting the content in `tiptap`

Before setting the content using `editor.commands.setContent()`, you should remove all `<br>` tags that have the class `ProseMirror-trailingBreak`. This will ensure that `tiptap` does not store these unnecessary tags, as it will add them again if required.

Here’s how to do that:

```js
let cleanedHtml = storedhtml.replace(/<br\s*class=["']ProseMirror-trailingBreak["']\s*\/?>/g, '');
// Use the cleaned HTML with setContent
editor.commands.setContent(cleanedHtml);
```

This will remove all occurrences of `<br>` tags with the class `ProseMirror-trailingBreak`, avoiding redundant tags being stored.

#### Step 2: Handle extra `<br>` spacing when passing the content to a PDF creator

If you're seeing extra `<br>` spaces when passing the content to a PDF creator, it's likely due to an extra `<br>` preceding the one with the `ProseMirror-trailingBreak` class. You can handle this by specifically removing the first `<br>` that appears before the one with `ProseMirror-trailingBreak` class.

Use this regex before sending the content to your PDF generator:

```js
let parsedValue = parsingValue.replace(/<br\s*\/?>\s*<br\s*class=["']ProseMirror-trailingBreak["']\s*\/?>/, '<br class="ProseMirror-trailingBreak" />');
```

This will remove the extra `<br>` that causes unnecessary space while keeping the correct formatting.

**Comment by mweidner037** [comment]
I created an extension to try to solve this: https://github.com/commoncurriculum/tiptap-extension-trailing-break

Instead of `editor.getHTML()`, you call `getHTMLWithTrailingBreaks(editor)`, which adds BRs to empty paragraphs and paragraphs that end with a blank line. These BRs are ignored when parsing (using a data- attribute), so you don't get extra blank lines when you setContent.
