### ISSUE TITLE
generateHTML / generateJSON with CodeBlockLowlight 

### ISSUE THREAD

**Issue by sonnyt** [ueberdosis/tiptap#1539]
**Description**
`generateHTML` / `generateJSON` methods in `@tiptap/html` pacakge does not produce highlighted HTML/JSON.

**Steps to reproduce the bug**
1. Try and generate either JSON or HTML.

**Expected behavior**
HTML produced by `generateHTML` should have lowlight code highligthing classes etc.

**Comment by hanspagel** [comment]
Thanks! That’s by design. You have two options to get syntax highlighting for the content:

Use tiptap to render the content and set it to editable: false.

Or add lowlight to the frontend and apply it on the rendered HTML.

**Comment by joelcolucci** [comment]
Hi @hanspagel. Thanks for your work! TipTap has been great to work with.

**Background**
We're working on a CMS that prioritizes the viewer experience. We send the complete HTML document to our readers with close to zero client-side JS.

**Question**
I'm working to understand the design decision to not output the same HTML the editor contains while editing. Is this due to complications with loading the editor from HTML and JSON?
