### ISSUE TITLE
Toggling code block on multiple lines, create seperate code blocks on every line.

### ISSUE THREAD

**Issue by Blakeinstein** [ueberdosis/tiptap#1585]
## Description
Copy and paste code from somewhere, then select the code, and click on toggle code block. A seperate code block is created for each line in the selection.

## CodeSandbox
Unnecessary, this can be reproduced on the tiptap.dev demo.

## Expected behavior
A single continuous code block should have been created. 

## Screenshot, video, or GIF

https://user-images.githubusercontent.com/42214598/125580325-b97c570b-b058-4b84-9510-691fd5589be0.mov

## Environment
 - operating system: Windows/MacOS
 - browser: Firefox/Chrome
 - tiptap version: `@tiptap/vue-2:^2.0.0-beta.39`

**Comment by philippkuehn** [comment]
This is a mix of some issues.

- If you paste some nested code lines as plain text, whitespace will be lost. So transforming that lines (paragraphs) to a code block afterwards is a bad idea at all.
- There are only line breaks within code blocks. So if you paste some html or plain text without knowing that it’s a code block it’s not possible to know that a new line should create a line break instead of a new block (paragraph)

At the moment I have no concrete idea how to fix this in an elegant way.
