### ISSUE TITLE
Is it possible to render <thead> within the editor?

### ISSUE THREAD

**Issue by tcampbPPU** [ueberdosis/tiptap#1753]
It seems like `<thead>` are always getting converted back into `<tbody>` tags. Is there are way I can get my `thead` tags to persist?

I need to have those tags rendered in the HTML since I am producing a PDF of the editor content and need to have tables that span several pages include those table header on each page the PDF overflows.

Below is example of the HTML I am injected into a custom Table component:
```html
<table>
    <thead>
        <tr>
            <th colspan="1" rowspan="1">
                <p></p>
            </th>
            <th colspan="1" rowspan="1">
                <p></p>
            </th>
            <th colspan="1" rowspan="1">
                <p></p>
            </th>
        </tr>
        <tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="1" rowspan="1">
                <p></p>
            </td>
            <td colspan="1" rowspan="1">
                <p></p>
            </td>
            <td colspan="1" rowspan="1">
                <p></p>
            </td>
        </tr>
    </tbody>
</table>
```
But then the editor reformat and converts them back
```html
<table>
    <tbody>
        <tr>
            <th colspan=\ "1\" rowspan=\ "1\">
                <p></p>
            </th>
            <th colspan=\ "1\" rowspan=\ "1\">
                <p></p>
            </th>
            <th colspan=\ "1\" rowspan=\ "1\">
                <p></p>
            </th>
        </tr>
        <tr></tr>
        <tr>
            <td colspan=\ "1\" rowspan=\ "1\">
                <p></p>
            </td>
            <td colspan=\ "1\" rowspan=\ "1\">
                <p></p>
            </td>
            <td colspan=\ "1\" rowspan=\ "1\">
                <p></p>
            </td>
        </tr>
    </tbody>
</table>
```

**Comment by hanspagel** [comment]
Thanks for the request! Unfortunately, I don’t think that’s possible (with a reasonable amount of work).

**Comment by jamesg-rimsys** [comment]
Thanks @hanspagel How would you suggest we approach an alternative solution or approach how to bring this into a custom component?

**Comment by tcampbPPU** [comment]
Thanks for the clarification @philippkuehn

**Comment by massifrg** [comment]
Please, take a look at this fork of mine: [prosemirror-tables-sections](https://github.com/massifrg/prosemirror-tables-sections).

Since I'm also using tiptap, it should not be too difficult to make an `extension-table-with-sections` for tiptap.
Just let me know if there's interest in such a project.

**Comment by mortmoe** [comment]
> Please, take a look at this fork of mine: [prosemirror-tables-sections](https://github.com/massifrg/prosemirror-tables-sections).
> 
> Since I'm also using tiptap, it should not be too difficult to make an `extension-table-with-sections` for tiptap. Just let me know if there's interest in such a project.

Did you ever make this extension-table-with-sections for tiptap? I'm using mui-tiptap to create a document editor for my users, which also needs to be able to export to pdf and would be nice to have the headers repeated for each page.

**Comment by massifrg** [comment]
No, I did not make that extension, though I'm also using tiptap along with prosemirror-tables-sections in another project of mine. So you can already use it without such an extension.

There I'm using these extensions from tiptap (here's an excerpt from the [package.json](https://github.com/massifrg/pundok-editor/blob/main/package.json) file):
```
    "@tiptap/extension-table-cell": "^2.6.6",
    "@tiptap/extension-table-header": "^2.6.6",
    "@tiptap/extension-table-row": "^2.6.6",
```
In my code, I'm defining a [schema](https://github.com/massifrg/pundok-editor/blob/main/packages/renderer/src/schema/helpers/PandocSchema.ts) with the tiptap nodes for:
- [Table](https://github.com/massifrg/pundok-editor/blob/main/packages/renderer/src/schema/nodes/PandocTable.ts) (actually, it's `PandocTable` because it models a table in Pandoc)
- [TableBody](https://github.com/massifrg/pundok-editor/blob/main/packages/renderer/src/schema/nodes/TableBody.ts)
- [TableHead](https://github.com/massifrg/pundok-editor/blob/main/packages/renderer/src/schema/nodes/TableHead.ts)
- [TableFoot](https://github.com/massifrg/pundok-editor/blob/main/packages/renderer/src/schema/nodes/TableFoot.ts)

**Comment by landsman** [comment]
I was looking for the same thing. Is it still not planned in official package?

**Comment by massifrg** [comment]
I'm not planning to do it myself, first I need to maintain prosemirror-tables-sections, because there's some broken code for relative column widths that must be expunged, and hopefully replaced with code that works.

But you could reopen this issue: maybe the tiptap team could look into prosemirror-tables-sections and adapt the code into an extension.

Here's some more information, so that you know better what to expect:
- I forked prosemirror-tables to support [Pandoc's table model](https://hackage.haskell.org/package/pandoc-types-1.23.1/docs/Text-Pandoc-Definition.html#t:Block), in a [visual editor of mine](https://github.com/massifrg/pundok-editor) that is based on tiptap
- I need tables with an optional head, one or more bodies and an optional foot: this is already achieved in [prosemirror-tables-sections](https://github.com/massifrg/prosemirror-tables-sections)
- I also need [relative column widths](https://hackage.haskell.org/package/pandoc-types-1.23.1/docs/Text-Pandoc-Definition.html#t:ColSpec) (and prosemirror table [Attrs](https://prosemirror.net/docs/ref/#model.Attrs) for them), which are not in `prosemirror-tables-sections` yet, although I made them work somehow in `pundok-editor`'s code; I plan to work on that, to move that feature directly into `prosemirror-tables-sections`, with an alternative implementation of the columnresizing plugin, not removing the existing one, so that you can decide which one to use in your code
- I recently upgraded the tiptap dependencies in the editor, and that caused an incompatibility between `prosemirror-tables-sections` and tiptap's tables-related extensions (a clash of the internal CellSelection ID); so I had to copy and paste tiptap code into the editor's, with slight modifications to make it work
- in case in the future I can't use `prosemirror-tables-sections` with tiptap, I'll consider writing tiptap extensions for it, or getting rid of tiptap in my editor (which looks harder, though)
