### ISSUE TITLE
Clearing/removing a nested list item does not remove the list item node

### ISSUE THREAD

**Issue by EasterPeanut** [ueberdosis/tiptap#1780]
**Description**
Not sure if considered a bug or me having a different expectation of the behaviour of nested lists (both ordered and bullet lists):

When you have a list of 3 levels deep:

- item 1
  - item 2
    - item 3

Clearing the content of the second item and then using backspace on that same node, the cursor jumps up one level (expected) leaving the second item intact (not expected).

**Screenshot, video, or GIF**
https://user-images.githubusercontent.com/7781165/130457081-290ef856-7e6e-4473-a44f-c207c0ea0dc4.mov

**Expected behavior**
I know you can delete the second item if you would first delete the nested items under the second item, but I kind of expect to remove the second list item node by using backspace, effectively replacing it with the third item.

**Environment?**
 - operating system: MacOS
 - browser: Firefox
 - mobile/desktop: desktop
 - tiptap version: v2

**Comment by philippkuehn** [comment]
Since this is the same behavior on https://prosemirror.net/ I don’t have plans to change that for now.

https://user-images.githubusercontent.com/2500670/130643177-4ebdebf8-5ef6-454c-aa0d-007f74277be7.mp4

You can create an issue at the prosemirror repo or create some custom commands for list handling if you want to.
