### ISSUE TITLE
Custom heading node view removes content when toggling level

### ISSUE THREAD

**Issue by tylerforesthauser** [ueberdosis/tiptap#1887]
**Description**
In a Vue 2 project, when extending the heading extension with a custom node view, the content of the heading node gets removed when toggling between heading levels.

**Steps to reproduce the bug**
1. Using the CodeSandbox linked below, attempt to change the top heading node from h2 to any other level using the menu buttons or the Control/Cmd + Alt + 1-6 key commands.
2. You'll observe that the existing text of the heading "Hi there," gets completely removed from the node.
3. What _does_ work is virtually everything else, including switching to/from any heading level to/from paragraph, switching to/from any other block-type node, and adding any mark to the heading text.

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
* Vue: https://codesandbox.io/s/tiptap-issue-template-forked-ev30v?file=/src/components/Tiptap.vue

**Expected behavior**
Just like using regular html output, the heading text should remain intact when switching between heading levels.

**Comment by philippkuehn** [comment]
This is indeed an interesting issue. It’s because dynamic `as` attributes are not really supported for node views (in vue). It is very untypical to change the DOM element of a node but for headings it makes sense. 

Under the hood Vue renders a new element, when changing a h1 to h2 for example. When doing so, Vue removes all child nodes from the DOM including the `contentDOM` (`<NodeViewContent>`). ProseMirror thinks you have removed that content and re-renders the heading node without it. Meh.

So I have to find a way to re-use the `contentDOM` element when `<NodeViewWrapper>` renders as a different tag. Not sure if this is possible to be honest.

As a workaround you can set a custom `update` method to your heading node view to ensure that ProseMirror re-renders (destroy and init) the node view when the level attribute changes.

```js
VueNodeViewRenderer(HeadingComponent, {
  update({ oldNode, oldDecorations, newNode, newDecorations, updateProps }) {
    if (oldNode.type !== newNode.type) {
      return false
    }

    // always re-render when level changes
    if (oldNode.attrs.level !== newNode.attrs.level) {
      return false
    }

    if (oldNode === newNode && oldDecorations === newDecorations) {
      return true
    }

    updateProps()

    return true
  },
})
```

The react implementation is not effected by this issue because we always have to add some wrapping elements around node views here (which have some other downsides tbh).

**Comment by tylerforesthauser** [comment]
Wow this makes so much sense! Thank you so much for not only taking the time to explain it but for the workaround as well!
