### ISSUE TITLE
Issue with ReactNodeViewRenderer and tippyjs-react caused by extension-collaboration

### ISSUE THREAD

**Issue by canegru** [ueberdosis/tiptap#1942]
**Description**

When using collaboration with a custom node and tippy-react, the following error occurs
`Cannot read properties of undefined (reading 'element')`

**Steps to reproduce the bug**
1. Create a custom node rendered by ReactNodeViewRenderer 
2. Make sure node contains **NodeViewContent**
3. Add a basic @tippyjs/react component
4. Add custom extension to the editor
5. Add collaboration to editor

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

https://codesandbox.io/s/tiptap-react-forked-ewun2?file=/src/custom-node/Component.tsx:703-726

**Environment?**
 - operating system:
 - browser:
 - mobile/desktop:
 - tiptap version: 2.0 beta 66

**Additional context**
If I conditionally render the tippy-react component, it seems to work. Refer custom-node/Component.tsx for an example.

Thank you so much for this wonderful editor, this is beyond amazing on what we can build with it.

**Comment by YousefED** [comment]
I'm also running into this, and think it's caused by the latest maybeMoveContentDOM refactor.

The code flow that's happening on my side is:

1. ReactNodeView.mount() instantiates `this.renderer = new ReactRenderer`
2. `new ReactRenderer` calls `this.render()`
3. This render invokes the react renderer which causes useEffect of NodeViewContent to be called, which calls maybeMoveContentDOM. This subsequently causes an error because the assignment (see step 1 above) to this.renderer in ReactNodeView hasn't been completed (we're still instantiating `ReactRenderer`)

**Comment by philippkuehn** [comment]
@YousefED Yes, you are exactly right. That causes the issue. I’m trying to find a solution.

**Comment by philippkuehn** [comment]
@YousefED waiting for your feedback here :) https://github.com/ueberdosis/tiptap/pull/1960
