### ISSUE TITLE
HorizontalRule extension: inconsistent behavior

### ISSUE THREAD

**Issue by cadars** [ueberdosis/tiptap#1964]
### What’s the bug you are facing?

Inserting an HorizontalRule produces different results depending on:
- How is it created, shortcut or command
- Where in the document it is created; first, last,  or in between nodes
- The presence of the StarterKit extensions (maybe because of GapCursor?)

### How can we reproduce the bug on our side?

With just the HorizontalRule extension: https://embed.tiptap.dev/preview/Nodes/HorizontalRule
- Type `---` or `___` or `***`, an empty `<p>` is created before the node.

With the StarterKit extensions: https://embed.tiptap.dev/preview/Examples/Default
- Type `---` or `___` or `***`, an empty `<p>` is created before the node.
- Empty the editor, click <kbd>**horizontal rule**</kbd>, this markup gets created:

  ```html
  <hr contenteditable="false">
  <p><br></p>
  <p><br><br></p>
  ```

( I am using the tiptap.dev examples but I also can reproduce these issues locally, with all dependencies updated)

### What did you expect to happen?

- Adding an horizontal rule with markdown shortcuts should not add any empty paragraphs **before** it.
- Adding an horizontal rule as the first node with the `setHorizontalRule` command should not add more than one empty paragraph **after** it.

### Anything to add? (optional)

As always, thanks for your time, and this amazing editor!

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by rfgamaral** [comment]
I came looking for this issue, and I just want to add a few things:

> Adding an horizontal rule with markdown shortcuts should not add any empty paragraphs before it.

This still happens, even after @philippkuehn commit above, and I agree that it shouldn't.

> What did you expect to happen?

IMO, an empty paragraph should be added **after** adding the horizontal rule with the Markdown shortcut, if it's the last node being inserted in the document, so that the cursor is placed after the horizontal rule, and the user can continue typing.

---

@cadars I'm wondering if you ended up working on a fixed version of this extension on your side? If so, do you think you could share that?

**Comment by autumninflab** [comment]
@bdbch 
Hi, :)
Is this issue will fix soon?
I have similar issue.

1. typing `---`, a horizontal rule created.
2. typing any character (without line break)
3. horizontal rule is disappeared.

I guess it's because cursor still on the horizontal rule.
so the cursor should place after horizontal rule.

https://user-images.githubusercontent.com/97175098/190402476-eee99985-e24e-460b-b35c-e9c78c25ad69.mov

https://user-images.githubusercontent.com/97175098/190402937-e325914a-ff68-4782-8fec-db65441b5b4f.mov
