### ISSUE TITLE
Paste still broken (2.0.0-beta.120)

### ISSUE THREAD

**Issue by nokola** [ueberdosis/tiptap#2003]
### What’s the bug you are facing?

Pasting things like `**bold**` or `*italic*` multiple times doesn't work anymore.

### How can we reproduce the bug on our side?

See updated https://codesandbox.io/s/tiptap-after-paste-bug-jjoxc and bug #2002  that still reproduces.

Broken paste in above codesandbox (click to play gif):
![paste_broken2](https://user-images.githubusercontent.com/6869225/136632601-46d1b431-1e6e-4bc4-a5f8-7e86b420ef87.gif)

And in my project. Note:  In my project I have a bit different settings than bold/italic from StarterKit, however used to work before. Not there's data loss, same as bug #2002 (click to play gif)
![paste_broken3](https://user-images.githubusercontent.com/6869225/136632659-675e9d01-4fef-44d5-a7ab-4072e9d9ad5a.gif)

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-after-paste-bug-jjoxc

### What did you expect to happen?

Paste to work without extra characters or losing data.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Ah, I know what is happening in the first gif. Because it’s already italic from the first paste, italic can’t applied a second time. But that is something I can fix. But note that the second `bold` is italic too because you pasted at the open end of `italic`.

The second gif shows a different issue. I would really like to know the config of your pasteRules because there seems to be a data loss. Can you share some code or provide a codesandbox with that config?

**Comment by philippkuehn** [comment]
found the issue. there is no issue with paste rules but with some input rule regex. input rule regex should not have the `gm` modifiers. paste rules regex should only have a `g` modifier. (see: https://github.com/ueberdosis/tiptap/commit/65eddf0e789c620a53d9bec9509b515211fb9b3f)
