### ISSUE TITLE
Rerendering on each ation with react

### ISSUE THREAD

**Issue by maxbaluev** [ueberdosis/tiptap#2158]
### What’s the bug you are facing?

After installation according to the manual, the main component is re-rendered several times at startup and then, after each text entry.

### How can we reproduce the bug on our side?

1. open https://codesandbox.io/s/fervent-goodall-g80ow?file=/src/App.js
2. open the console log and see that 'start' is output multiple times.

### What did you expect to happen?

Don't know

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Yeah that’s how the editor works. The component, which uses `useEditor`, is re-rendered for each change. This is useful for rendering menu buttons in it. So you should probably put the editor in a separate component instead.

```jsx
function Editor() {
  console.log("log on every editor change");

  const editor = useEditor({
    extensions: [StarterKit],
    content: "<p>Hello World!</p>"
  });

  return <EditorContent editor={editor} />;
}

export default function App() {
  console.log("log once");

  return <Editor />
}
```

**Comment by Slapbox** [comment]
@philippkuehn it re-renders even when nothing changes. Is it possible to prevent that? Eg an empty transaction occurs and the entire editor and everything in it re-renders. I know this seems like a non-issue but it would make our lives a lot easier if it didn't re-render for a transaction that changes nothing at all.

**Comment by Slapbox** [comment]
@philippkuehn @bdbch it re-renders even when nothing changes. Is it possible to prevent that? Eg an empty transaction occurs and the entire editor and everything in it re-renders. I know this seems like a non-issue but it would make our lives a lot easier if it didn't re-render for a transaction that changes nothing at all.

Even if we filter such transactions out with `filterTransaction`, it still re-renders everything.

----

I guess it's because of this code:

https://github.com/ueberdosis/tiptap/blob/42039c05f0894a2730a7b8f1b943ddb22d52a824/packages/react/src/useEditor.ts#L105-L113

It seems very inefficient to `forceUpdate` for every transaction.

Surely adding a trivial check like this would be less expensive than forcibly re-rendering, no?

```
  instance.on('transaction', (tr) => {
    if (
      tr.docChanged ||
      Object.keys(tr.meta).length > 0 ||
      tr.selectionSet ||
      tr.storedMarksSet
    )
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (isMounted) {
            forceUpdate()
          }
        })
      })
  })
```

**Comment by Slapbox** [comment]
Actually my proposed check is sort of a wash when only a small number of transactions are non-modifying, and I realized `tr.setMeta('preventDispatch', true)` exists while investigating and testing.

It would be good if that were documented.
