### ISSUE TITLE
Table dragging doesnt work, it duplicates the table

### ISSUE THREAD

**Issue by marclave** [ueberdosis/tiptap#2250]
### What’s the bug you are facing?

When adding a drag handle and makign a table draggable, it will drag the table howeber it will not remove the older table so you end up duplicating it

### How can we reproduce the bug on our side?

Go to this codesandbox, click and hold the drag button then drag the table below the paragraph of text and it will duplicate.

https://codesandbox.io/s/nameless-dew-0wmnx?file=/src/components/TipTap.vue

### Can you provide a CodeSandbox?

https://codesandbox.io/s/nameless-dew-0wmnx?file=/src/components/TipTap.vue

### What did you expect to happen?

We expect the table to be moved, so the empty table where the original table was should be deleted

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Hey! Unfortunately, I don't see any way that this can work currently. The problem is somehow triggered by the [`tableEditing`](https://github.com/ProseMirror/prosemirror-tables/blob/6b16ed3cf306886f2c169aebbe60701e1ac2deac/src/index.js#L26-L66) plugin. You can disable that but you will lose many functions. Example: https://codesandbox.io/s/competent-ritchie-wy7kg?file=/src/App.vue

We use `prosemirror-tables`, which unfortunately is currently not maintained anymore. Maybe we will do a re-write ourselves someday, but this is a huge project and will take a long time.

**Comment by rakesh-splose** [comment]
Hey,

Setting attribute allowTableNodeSelection: true, resolved my issue. Hope this will work for you too. Thanks
  
  Table.configure({
    **allowTableNodeSelection: true,**

    resizable: true,
    lastColumnResizable: false,
  }),
