### ISSUE TITLE
Better interaction between formatting options in lists

### ISSUE THREAD

**Issue by holtwick** [ueberdosis/tiptap#2261]
### What’s the bug you are facing?

If I'm inside a bullet list, changing to "paragraph", "heading" or  "blockquote" does not work.

### How can we reproduce the bug on our side?

Just try it in your demo editor.

### What did you expect to happen?

All "block level" actions should interact correctly with each other. Especially those that exclude each other like list and heading.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Converting list items to text blocks like paragraphs or headings should work better now with [this patch](https://github.com/ueberdosis/tiptap/commit/f2ced6971d60c555ce1e6bc7116fe0168f018bf1).

But blockquotes behave differently, since they can contain block nodes themselves. What would you expect here? 

1. Should the `listItem` be converted to a `blockquote` and then contain a `paragraph` with its text? (should be easy)
2. Or should the entire `listItem` be moved to a `blockquote`. For this the moved `listItem` must be wrapped into a new list. (more complex)

Feel free to create a new issue for the blockquotes.

**Comment by philippkuehn** [comment]
The behavior of blockquotes across multiple nodes is also interesting. Because a `NodeRange` with a specific `depth` is calculated for the ProseMirror `wrapIn` command, in this case also the `paragraph` and the whole `bulletList` is wrapped instead of `paragraph` and the first `listItem`:

https://user-images.githubusercontent.com/2500670/145825156-4db63651-19fc-4467-86a8-48d45368d7f8.mp4

So a third option would be to wrap the entire list when trying to wrap a `listItem`. What do you think?

**Comment by holtwick** [comment]
I like it the way it behaves in the video 👍

**Comment by philippkuehn** [comment]
Just to be clear: This is how it already works now. See:

https://user-images.githubusercontent.com/2500670/145829222-8e30a342-c2a1-4452-ad8d-eb54ffafbf0a.mp4

The calculation of the NodeRange depth is only wrong if the same is tried within a list. But I could fix that so that it behaves the same within lists.

**Comment by holtwick** [comment]
I see. Indeed, that list only blockquote bug is one I experienced as well. A fix would be very welcome. Thanks!

**Comment by philippkuehn** [comment]
Haha. I was more trying to say that I don`t like to split the `list` 😅

It seems like a lot of work for a case that has only been reported once.

**Comment by holtwick** [comment]
You don't have to split the list. You showed a selection that started and ended inside the list. Click on blockquote did nothing. I consider this to instead extend the scope to the whole list (`<ol>` if you like instead of `<li>`) as it does, if one end of the selection is outside the list.

I think the details are what makes a text editor great 😉
