### ISSUE TITLE
Vue 3 useEditor is typed as Ref<Editor>, but previous typing Ref<Editor|undefined> was more accurate

### ISSUE THREAD

**Issue by dospunk** [ueberdosis/tiptap#2351]
### What’s the bug you are facing?

The useEditor function for the vue 3 tiptap package is typed as returning a `Ref<Editor>`, but it used to be typed as `Ref<Editor | undefined>`  which was more accurate because the editor isn't created until the `onMounted` hook runs. 

### How can we reproduce the bug on our side?

Try to use the `ref` returned by `useEditor` in the `setup` function. See the provided CodeSandbox console for example.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/objective-wildflower-o0f4v?file=/src/App.vue

### What did you expect to happen?

I expect the typing of useEditor to reflect what is actually returned by the function.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This was introduced with this [patch](https://github.com/ueberdosis/tiptap/commit/b5b9363b49ecf64550c9df707b02d02854cc8c98#diff-c79287bdd112b4264f53e38c24a0de06a0a7cf50db8134c29087ef8c44d94124) because the build was broken. But for some reason this is working again so [I reverted these changes](https://github.com/ueberdosis/tiptap/commit/3ba3afbea38b9b46b5d164e0d6a374ecd0ef63c6).

**Comment by dospunk** [comment]
Rad! Thank you very much :D
