### ISSUE TITLE
New line do not work if Suggestion used

### ISSUE THREAD

**Issue by nucleartux** [ueberdosis/tiptap#2381]
### What’s the bug you are facing?

New line do not work if Suggestion used.

### How can we reproduce the bug on our side?

1. open https://tiptap.dev/api/nodes/mention
2. Type on end of any line "@foo"
3. Press "enter"
4. Nothing happens

### What did you expect to happen?

New line (paragraph) should be created

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Hey, this is because when typing `@foo` there is still an active suggestion. It wasn’t visible until now but [this patch](https://github.com/ueberdosis/tiptap/commit/1dcbefd08bdbaec2191f2e529a9f92181d8f4a54) should help. Nevertheless, it is not fixed that you can’t press `enter` because the suggestion is still active. The only way to exit a suggestion is to press `space` for now. There is [another issue](https://github.com/ueberdosis/tiptap/issues/214) for this already so I’m closing this here.
