### ISSUE TITLE
toggleTaskList flattens nested bullet lists

### ISSUE THREAD

**Issue by bkempe** [ueberdosis/tiptap#2428]
### What’s the bug you are facing?

The `toggleTaskList` command flattens an existing nested bullet list it's invoked in.

### How can we reproduce the bug on our side?

Go to https://tiptap.dev/
In the example editor, create a bullet list like this:
- 1
  - 2
    - 3

With the cursor on the "3", click the "Task List" button.

### What did you expect to happen?

Only the bullet item itself or only the nested bullet item list should be converted to a task list.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by itsmingjie** [comment]
Hi! I'm one of the program coordinators of a nonprofit program called [CodeDay Init](https://labs.codeday.org/), and we partner with colleges to help CS students make their first open-source contribution. 

We'll claim this issue for now and a group of students will be on it soon with mentorship! If this issue is no longer relevant, please let me know.

**Comment by philippkuehn** [comment]
Oh great. Good luck :)

**Comment by max-nextcloud** [comment]
Hi,

I've been looking into this problem some. Would love to see it fixed. I'll add my thoughts here in case they might be helpful.

I'd like to see `TaskLists` behave like `OrderedLists` and `BulletLists` when switching between them. When the cursor is on a bullet list item and i trigger `toggleOrderedList` the entire list becomes an ordered list. Parent lists and sublists remain what they are.

For ordered and bullet lists this switch is (somewhat) easy because they only need to switch the tag for the entire list and not the tags for the items.
Task lists however by default may not contain listitems - only taskitems. And bullet and ordered lists may only contain listitems.
So it's not easy to convert one into the other (to my knowledge). If i first convert the entire List the items are invalid content and if i try to convert an item it's invalid as well. I am not aware of a mechanism to convert both at the same time.

So I looked into building all three list types with a single item type. The item type would need a `checked` attribute for the todo list items to properly work - but it would only apply in todo lists. So i extended ListItem like that and configured the TaskList to contain ListItems.

The List items in the Task list should still render differently - they need to display the checkbox etc. In order to achieve that i tried to change the `renderHTML` function. But so far there is no way (that i know of) for the list item to tell it's inside a task list. The `renderHTML` function only gets the node and the HTML Attributes - no information about the parent node or the state the document is in.

So even though we can work around the schema limitations by allowing the same items in all three list types we still need an attribute to distinguish them. Using that attribute in `renderHTML` and loading it initially in `parseHTML` is somewhat easy. But when the list is toggled to a different list type all the item children in the list need to have the attribute changed. This is where i am at right now. Looks like it would require a `updateChildrenAttributes` function that updates the attributes of all direct children (and only the direct children in order to not affect nested lists).

**Comment by bkempe** [comment]
@max-nextcloud Thanks for looking into this. Looks like ReMirror has accomplished it, see the [Demo](https://remirror.io/) and [Source Code](https://github.com/remirror/remirror/tree/main/packages/remirror__extension-list/src)

**Comment by max-nextcloud** [comment]
https://github.com/remirror/remirror/blob/826670eaba81d589fbad8037867ba8628b76ec3a/packages/remirror__extension-list/src/list-commands.ts#L315 is the most important code in question. They rebuild the entire list with the new list node and new item nodes. That way each list type can have its specific item type just like it does in tiptap right now. Creating an invalid state is avoided by having building the new list from scratch. Actually seems like a good approach.

**Comment by bkempe** [comment]
This is another implementation: https://github.com/bangle-io/bangle.dev/blob/d0a64c642ce4840404fa6ed443bbbfcefd555123/components/base-components/bullet-list.ts#L116

**Comment by susnux** [comment]
Still an issue!

**Comment by fredrivett** [comment]
+1 on this, still an issue, not currently a top priority for us but a nice to have, if we prioritise it as a team will update here if we make any progress

**Comment by mikekreeki** [comment]
This would indeed be really cool 👍
