### ISSUE TITLE
Doc on vanilla javascript is weird

### ISSUE THREAD

**Issue by caramboleyo** [ueberdosis/tiptap#2486]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/installation#vanilla-java-script

### What part of the documentation needs improvement?

It says vanilla javascript but then it mixes up nodejs:

```
import { Editor } from '@tiptap/core'
import StarterKit from '@tiptap/starter-kit'
```

with vanilla javascript:
```
document.querySelector('.element')
```

There is no document in nodejs and there are no package imports in vanilla javascript.

This makes no sense.

### What is helpful about that part?

Absolutely nothing.

### What is hard to understand, missing or misleading?

As described above

### Anything to add? (optional)

“Frameworks” are bloatware.

**Comment by hanspagel** [comment]
Phew, thanks for the feedback.

Actually, `import` does work in the browser environment now:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

And vanilla JavaScript, doesn’t mean no build system, for example Vite (which is really amazing) helps with that, even for vanilla JavaScript apps:

https://vitejs.dev/guide/#trying-vite-online

That said, I feel you. All that can be very confusing. I’ll check what we can do to simplify the guide. Thanks!

**Comment by binyamin** [comment]
> Actually, `import` does work in the browser environment now:

@hanspagel In fairness, the example in the docs uses node-style imports. In a browser environment, you would link to a local file or a CDN. Unless you're using a build tool, but best not to assume.

**Comment by DTBob** [comment]
Any chance of a working example using vanilla JS without node imports? I've had a pretty good go at getting it working but to no avail. Much appreciated if someone can help!

**Comment by danielpunkass** [comment]
Came across this ticket after also being confused that the "vanilla" example didn't work out of the box (at least with Safari on Mac). I was hoping for a straight-forward JS-only example to start playing with.

**Comment by binyamin** [comment]
@danielpunkass @DTBob Here's a vanilla-JS, browser-compatible solution. For more details, see [MDN's browser-compatibility chart for the `import` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#browser_compatibility).

You can import almost any NPM package as an ES Module from [esm.sh](https://esm.sh) (eg. `import MyPackage from "https://esm.sh/my-package"`). In general, you can also use [Skypack](https://skypack.dev) (eg. `import MyPackage from "https://cdn.skypack.dev/my-package"`). In this case, it gave me an error.

Remember to import the JS file as an ES Module: `<script type="module" src="...". ></script>`.

```js
import { Editor } from 'https://esm.sh/@tiptap/core'
import StarterKit from 'https://esm.sh/@tiptap/starter-kit'

new Editor({
  element: document.querySelector('.element'),
  extensions: [
    StarterKit,
  ],
  content: '<p>Hello World!</p>',
})
```

**Comment by danielpunkass** [comment]
Thanks @binyamin ! I went one step further and packed it all in a single file and it seems to work. Great for early/easy hackjing around: 
`<head>
<script type="module">
import { Editor } from 'https://esm.sh/@tiptap/core'
import StarterKit from 'https://esm.sh/@tiptap/starter-kit'

new Editor({
  element: document.querySelector('.element'),
  extensions: [
    StarterKit,
  ],
  content: '<p>Hello World!</p>',
})
</script>
</head>
<body>
<div class="element"></div>
</body>
`

**Comment by bdbch** [comment]
I think the issue here is that the current javascript documentation is an example for when you use a build system but no framework. (As you can see here with Codesandbox: https://codesandbox.io/s/white-platform-l27lyz?file=/src/index.js)

We could solve this problem, by providing an example on how to work with Tiptap and CDNs.

**Comment by binyamin** [comment]
@hanspagel Can you updates the docs please? See https://github.com/ueberdosis/tiptap/issues/2486#issuecomment-1126265433

**Comment by binyamin** [comment]
It's stale because maintainers haven't seemed dealt with it.

**Comment by remingtonc** [comment]
I have been banging my head against this for an hour and cannot determine how to get the editor to load its upper bar of extensions & helpful tools. When I do load - I receive a single line editor, with some amount of extension support e.g. `code` works in the below, but no editor buttons. Do I need to do something undocumented?

<img width="745" alt="Screenshot 2023-03-03 at 2 16 45 PM" src="https://user-images.githubusercontent.com/16908622/222840253-9881b2ee-4db4-46b0-a2e0-d81b37bcad73.png">

I was hoping it had something to do with how I was using rollup to package the modules - but even using the recommended CDN method above it simply does not display.

**Comment by bdbch** [comment]
@remingtonc Tiptap doesn't include an editor bar. While we already have ideas to provide a UI in the future for now Tiptap is **headless** (doesn't come with markup or styling).

If you are using vanilla javascript you could bind your own buttons like this:

```js
<html>
  <head>
    <script type="module">
      (function() {
        // load tiptap from esm.sh here

        const editor = new Editor({ ... }) // add your configuration, extensions, content, etc.

        const buttons = {
          bold: document.querySelector('[data-tiptap-button="bold"]'),
          italic: document.querySelector('[data-tiptap-button="italic"]'),
          underline: document.querySelector('[data-tiptap-button="underline"]'),
        }

        const setButtonActive = (button, mark) => {
          if (editor.isActive(mark)) {
            button.classList.add('active')
          } else {
            button.classList.remove('active')
          }
        }

        buttons.bold.addEventListener('click', () => {
          editor.chain().focus().toggleBold().run()
          setButtonActive(buttons.bold, 'bold')
        })

        buttons.italic.addEventListener('click', () => {
          editor.chain().focus().toggleItalic().run()
          setButtonActive(buttons.bold, 'italic')
        })

        buttons.underline.addEventListener('click', () => {
          editor.chain().focus().toggleUnderline().run()
          setButtonActive(buttons.bold, 'underline')
        })
      })()
    </script>
  </head>

  <body>
    <div class="editor-toolbar">
      <div class="editor-toolbar__buttons">
        <button class="editor-toolbar__button" data-tiptap-button="bold">Bold</button>
        <button class="editor-toolbar__button" data-tiptap-button="italic">Italic</button>
        <button class="editor-toolbar__button" data-tiptap-button="underline">Underline</button>
      </div>
    </div>
    <div class="my-editor" id="editor"></div>
  </body>
</html>
```

Didn't test this in a running environment but this should world.
Hope this helps.

**Comment by bdbch** [comment]
Here is a quick Codesandbox with my example running in a single html file:
https://codesandbox.io/s/throbbing-smoke-now37q?file=/index.html

I'll update the docs accordingly.

**Comment by remingtonc** [comment]
@bdbch My apologies - I forgot the headless portion and was instead assuming the default examples were pre-wired!
Scrolling down in the https://tiptap.dev/examples/default - I now see all the button wiring.

Thank you for the example. I had believed this was a vanilla issue.

For posterity, the rollup I use to do this locally and not via CDN is from: https://stackoverflow.com/a/71626945

```
npm install --save-dev rollup @rollup/plugin-node-resolve @rollup/plugin-replace @rollup/plugin-terser
npm install @tiptap/core @tiptap/starter-kit
# create below files first
npx rollup -c
```

`index.js`
```javascript
import { Editor } from '@tiptap/core'
import StarterKit from '@tiptap/starter-kit'
export { Editor, StarterKit }
```

`rollup.config.js`
```javascript
import replace from "@rollup/plugin-replace";
import terser from "@rollup/plugin-terser";
import { nodeResolve } from "@rollup/plugin-node-resolve"

export default {
    input: "index.js",
    output: [
        {
            file: "../routes/static/js/tiptap-rollup.js",
            format: "iife",
            name: "window",
            extend: true
        },
        {
            file: "../routes/static/js/tiptap-rollup.min.js",
            format: "iife",
            name: "window",
            extend: true,
            plugins: [ terser() ]
        }
    ],
    plugins: [
        replace({
            "process.env.NODE_ENV": "'production'",
            "preventAssignment": true
        }),
        nodeResolve()
    ]
};
```

And `../routes/static/js/tiptap-rollup.min.js` is usable then via HTML (running from a web server in this case not raw files):
```
<html>
    <head>
        <title>TEST</title>
        <script src="static/js/tiptap-rollup.min.js"></script>
    </head>
    <body>
        <h1>MING</h1>
        <div class="story"></div>
        <script>
            editor = new Editor({
                element: document.querySelector('.story'),
                content: '<p>Example Text</p>',
                extensions: [
                    StarterKit,
                ],
            })
        </script>
    </body>
</html>
```

**Comment by bdbch** [comment]
Great that my demo helped out a bit. If you have questions let me know.

**Comment by binyamin** [comment]
@bdbch I'd be happy to work on this, if you can explain how to run the docs locally.

**Comment by bdbch** [comment]
Hey @binyamin sorry for the late answer. The docs are currently built together with our Tiptap website which is server side rendered. Right now there's no way to manually build the docs locally.

You could do it blind - since we don't do any special layout things it should work out fine if you just do text changes.

**Comment by bdbch** [comment]
I took a look at our current docs and I think they are understandable.

I added a small info notice why we rely on module imports (mostly because of the modularity of Tiptap)

Since we don't support other ways of using Tiptap in Vanilla JS right now I'd close this issue.

**Comment by caramboleyo** [comment]
They are not and the cdn link is broken.
But i never used it anyway, no proper docs and don't know what vanilla means.
I dont know why a little group of people tries to force those frameworks or the node compilation way on the majority but there are tons of better alternatives anyway.

**Comment by bdbch** [comment]
I checked the CDN link and it works for me (sends me to https://tiptap.dev/installation/cdn)

What exact problem are you running into. Tiptap has a lot of cross dependencies inbetween each other and just bundling everything into one js file for "vanilla" js usage is basically breaking the idea behind Tiptap (itself being modular).

I don't exactly know what the problem is with esm.sh or any other CDN js provider as you just need to use `<script type="module"></script>` and imports to those hosted Tiptap versions to make it work. 

https://codesandbox.io/s/peaceful-ramanujan-xphvv3?file=/index.html

What problems are you running into with this solution? @caramboleyo

**Comment by lofcz** [comment]
The current problem is most of the **interesting** features have documentation only for React / Vue, only StarterKit and start from-scratch are covered for vanilla. Are there any plans to cover the extensions?

**Comment by cwmoss** [comment]
@bdbch your codesandbox link describes the problem at best: it just doesn't work. 

for me it's really hard to understand why this is such a big problem. you make this editor available for many frameworks, so i guess it's written in plain javascript. for me so far it has worked with vue fine. but using it without a framework runtime, with or without a node build (tested vite) just fails. why is that? but you are in good company. lexical also fails in this regard. they even think, that typescript equals to vanilla lol

**Comment by Petercopter** [comment]
I'm using Ruby on Rails with Stimulus Javascript. The vanilla docs still leave you hanging. I was able to get the editor instantiated no problem, but then the next step is 'styling', and it goes right into React things.

The codesandbox provided by @bdbch (thanks!) is more helpful than the documentation. It would be really nice if Vanilla JS had a demo here https://tiptap.dev/docs/examples/basics/default-text-editor like React, Vue and Svelte have. You could pretty much copy the codesandbox and that would get people started.

**Comment by bdbch** [comment]
Hey everyone

Thanks again for all the thoughtful feedback here. I’m going to reopen this issue because we’ve seen that the current “Vanilla JavaScript” section still causes confusion for people who are not using a framework.

To clarify our perspective:
Tiptap’s API works exactly the same in plain JavaScript as in React/Vue/Svelte, so most of the logic and examples are directly translatable. That’s why we haven’t focused on separate JS examples so far. However, it’s clear that the onboarding experience for "no framework" users can be improved — mainly around setup and expectations.

Here’s what we’re planning to review:

- Clarify what **"Vanilla JS"** means in our context (e.g. “no framework, but still using modern ESM imports or bundlers like Vite”).
- Add a fully working CDN-based example that runs directly in a <script type="module"> block (using esm.sh or similar), so people can test Tiptap in seconds.
- Update the styling section to briefly mention how to include the base styles and how that works without React or Vue components.
- Add a small Vanilla JS example on the Examples page, similar to the React/Vue/Svelte ones.

We’re not planning to duplicate every example or extension in “pure JS”, since the underlying API and logic are identical — but we want to make sure the documentation helps people get started smoothly regardless of tooling.

I’ll take another pass at this soon and will share updates when we have the new structure drafted.
If anyone has ideas or links to working examples you’d like us to include, feel free to drop them here.
