### ISSUE TITLE
Pass Ref to the underlying component in custom extensions

### ISSUE THREAD

**Issue by anasaijaz** [ueberdosis/tiptap#2517]
### What problem are you facing?

Right now ( If I am not wrong  ) custom extensions that use their own components or even prebaked extensions do not have a feature to pass events or even control the component through a ref

### What’s the solution you would like to see?

It would be amazing if the extension can expose a ref for greater control over component 

### What alternatives did you consider?

If raw events can be passed to an extension
Right now I am using the handleClick method of the Editor and getting the `event.target` to get a hold over the element but this is not an elegant solution to directly access DOM

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
There are no node instances in ProseMirror. If you need to add some click handler for example you can do this within node views or with a global handler. In this global handler you have to update a "position" instead of a "node instance". That’s how ProseMirror works so there is no way to change that.
