### ISSUE TITLE
No way to add a CodeBlock into a ListItem

### ISSUE THREAD

**Issue by veesahni** [ueberdosis/tiptap#2627]
### What’s the bug you are facing?

The underlying data model supports ```CodeBlock``` inside ```ListItem``` .. but it's not possible via the interface.

The \`\`\` shortcut does nothing in a ListItem
The ```toggleCodeBlock()``` inside a ListItem causes the list to close and then starts the CodeBlock

However, you can cut/paste a code block into a ListItem, because the underlying model actually supports this:

![image](https://user-images.githubusercontent.com/705483/158721818-d7df2b7d-7453-4045-b510-adaa459f1363.png)

Note: prosemirror can handle this fine.  On prosemirror.net: start a list, click the code button, and you've got a code block inside a list item.

### How can we reproduce the bug on our side?

* On tiptap.dev, start a list
* Click the code button

### What did you expect to happen?

A code block should be opened inside the ListItem

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
I think this is a regression from [this patch](https://github.com/ueberdosis/tiptap/commit/ded6f9618fb588f2c259edc9bc77415f8723431c) to fix [this issue](https://github.com/ueberdosis/tiptap/issues/2302).

**Comment by veesahni** [comment]
Not sure it makes sense to auto-close stale bugs?  The bug is still there. @philippkuehn

**Comment by frankchn** [comment]
Hi @philippkuehn this is still happening on the latest version.

**Comment by bdbch** [comment]
Thanks for the ping @rfgamaral

I reopened this issue.

**Comment by sjdemartini** [comment]
not stale

**Comment by bdbch** [comment]
The reason why this happens is, because the listItem schema says that it can include `paragraph block*`(see https://github.com/ueberdosis/tiptap/blob/develop/packages/extension-list-item/src/list-item.ts#L23)

That means the first item can never be turned into a codeBlock node and it's not possible by normal means to create a sibling node via `enter`.

If you want to you can extend the ListItem node and change it's schema. I think that should work but could potentially break things (specially with code block exiting.)
