### ISSUE TITLE
can not add normal text after link, when link text doesn't match URL schema

### ISSUE THREAD

**Issue by littlee** [ueberdosis/tiptap#2671]
### What’s the bug you are facing?

unable to add normal text after a link whose text content is not an URL

```html
<a href="...">http://some.com</a> works;

<a href="...">some com</a> not working
```

### How can we reproduce the bug on our side?

- focus at the end of the first link, press space, can add normal text
- focus at the end of the second, press space, can not add normal text

### Can you provide a CodeSandbox?

https://codesandbox.io/s/epic-kapitsa-zffu7f?file=/src/App.vue

### What did you expect to happen?

press space at the end of a link node should work in the same way, despite of its text content

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
That’s how marks work by default. A space doesn’t cancel links, bold, italic, etc. You can change the behavior with `inclusive` but that means that any typed character at the end of the link is not part of the link anymore.

```js
Link.extend({ inclusive: false })
```

It’s working for your first link because the `autolink` option is turned on by default (which detects typed links).

**Comment by littlee** [comment]
@philippkuehn hi, adding `inclusive: false` causes another bug I think 😂 

https://codesandbox.io/s/jovial-worker-i0bj9z

can not type space in the middle of link, which will break the link to part link and part text
