### ISSUE TITLE
Suggestion menu appears when clicking on potential mention

### ISSUE THREAD

**Issue by grantmagdanz** [ueberdosis/tiptap#2680]
### What’s the bug you are facing?

Clicking an incomplete mention causes the suggestion menu to appear.

### How can we reproduce the bug on our side?

1. Go to the mention example on the tiptap website: https://tiptap.dev/examples/suggestions
2. Type `@win` and then `esc`. Do not complete the extention.
3. Type something else after
4. Click on `@win` (may need to click twice)
5. Mention menu will appear

https://user-images.githubusercontent.com/9100467/161542187-153c6d08-ee8f-4364-abc4-d808a1cb268a.mp4

### What did you expect to happen?

After a user indicates they do not want to mention (e.g. they hit `esc`) the mention should act as plain text.

### Anything to add? (optional)

This is particularly confusing because it happens when the editor is not in `editable` mode. 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by scottsidwell** [comment]
I had some time to look into this today (separate to the maintainers) and have some comments to add.

Firstly, you've actually mentioned two bugs, the second one being that suggestions should not be triggered when `editor.isEditable === false`. Since this was fairly straightforward, I raised a fix for this in https://github.com/ueberdosis/tiptap/pull/2692.

Back to the main issue you've raised here, the root cause appears to be an underlying design decision of how the suggestions plugin works. My understanding of how it works, is that (when you have an empty selection) it looks backwards in the current text block to see if the text that precedes your cursor matches the rough semantics of `${char}.*`. Since this is reactive, i.e. it waits for change in the editor state, and then tries to decide whether to display the suggestion UI, there's no mechanism for it to **not** show the suggestion UI when you select that text again in the future.

I'll let the maintainers weigh in here on how they see suggestions evolving, since any change to this behaviour will likely have flow on impacts to other parts of the UX here. e.g. this would cease to work

https://user-images.githubusercontent.com/38820281/162371171-3858950b-65d0-4137-8df2-54b28d426074.mov

**Comment by grantmagdanz** [comment]
@scottsidwell Thank you for the reply and the fix! It's very much appreciated. 

Huh, interesting. Thanks for looking into it and that makes sense. I'll see if the maintainers will weigh in. Getting it to not show up when not editable is already a big UX improvement.

**Comment by jessicalc** [comment]
@scottsidwell Thanks for disaggregating the two issues so succinctly and for fixing the read-only editor behavior! 


I'm also interested in hearing about how to let people "opt out" of choosing something from the suggestion menu. Following!

**Comment by bdbch** [comment]
@jessicalc @grantmagdanz do you think this behaviour should be optional?

As already discussed, the current solution is to check the current Textblock for a specific pattern in front of the current curserPos.

I don't have an exact idea yet where to "store" that a user saw a suggestion menu and decided not to use it.

Happily taking suggestions before working on it. 🤞
