### ISSUE TITLE
Controls disappeared

### ISSUE THREAD

**Issue by airon-tark** [ueberdosis/tiptap#2703]
### What’s the bug you are facing?

Hey guys. I am using this tiptap version

    "@tiptap/extension-image": "^2.0.0-beta.27",
    "@tiptap/react": "^2.0.0-beta.108",
    "@tiptap/starter-kit": "^2.0.0-beta.183",

after we add HTTPS (SSL certificate), controls disappeared

<img width="696" alt="Снимок экрана 2022-04-12 в 15 41 13" src="https://user-images.githubusercontent.com/54197112/162919611-011dccab-8034-4b04-a135-b84cf4f6c93b.png">

Thanks in advance =)

### How can we reproduce the bug on our side?

I don't know. Controls just become invisible for us.

### What did you expect to happen?

Controls visible

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.
- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @airon-tark.

Since we don't have a demo or any additional info we can work with I'd just take a guess. Could it be that you have mixed URLs with and without https: in your code that could lead to your assets/icons not loading anymore?

Some questions:

1. Are there any information in your browser console?
2. Are there errors in your console or network tab?
3. Do the buttons still work - but just the visuals are missing?

**Comment by bdbch** [comment]
Could you verify if it's HTTP/S mixed content issue?
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

**Comment by bdbch** [comment]
Closing this because the issue is stale and controls or buttons are not part of Tiptap itself.
