### ISSUE TITLE
isActive() returns false if multiple text styles are in effect in selected text

### ISSUE THREAD

**Issue by raarts** [ueberdosis/tiptap#2745]
### What’s the bug you are facing?

If you select some text, which contains multiple styles (I tried bold, italic, underline) the isActive('bold') functions return false.
See below for how to reproduce.

### Which browser was this experienced in? Are any special extensions installed?

All browsers.

### How can we reproduce the bug on our side?

1. Go to the default example on the site. 
2. Make one word bold. 
3. Scroll the cursor in and out of that word, and see the bold button change. 
4. Select that word with the mouse. Again the bold button indicates the style.

Now do the same with two words, one of which is bold, and the other one is italic.
On selecting both words, the buttons do not 'light up'. Scrolling the cursor using the arrow keys works.

Interestingly enough, if you click on the first letter of a bold (or italic) word, and slowly pull the mouse to the right (selecting character by character), as soon as you cross a space, isActive() stops returning true, even if the next word is italic too.

So maybe the bug should be: isActive() stops returning true if it finds blanks in the selection.

### Can you provide a CodeSandbox?

Not necessary

### What did you expect to happen?

If I select a bit of text, I would expect all relevant buttons to light up. (isActive() to return true).

### Anything to add? (optional)

I was migrating here from remirror and their example does not exhibit this behavior.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
https://user-images.githubusercontent.com/6538827/175809433-8518c9b2-0666-4251-9740-dc7747a10b11.mp4

Moving the cursor by keyboard just works fine. The only thing that I could reproduce is that when I select from the em to strong - the setActive works fine for both - but if I start my selection the bold node and move over to the em node it breaks.

I guess because `getMarksAcross` is only working in one direction.

**Comment by bdbch** [comment]
https://user-images.githubusercontent.com/6538827/175809433-8518c9b2-0666-4251-9740-dc7747a10b11.mp4

Moving the cursor by keyboard just works fine. The only thing that I could reproduce is that when I select from the em to strong - the setActive works fine for both - but if I start my selection the bold node and move over to the em node it breaks.

I guess because `getMarksAcross` is only working in one direction.

**Comment by raarts** [comment]
I can still reproduce it:

https://user-images.githubusercontent.com/3168197/176024738-a33c861d-3488-4cc1-a5c4-7e3c268a181e.mov

**Comment by svenadlung** [comment]
@raarts thank you for the video. I was able to reproduce the behaviour. We are looking into it.

**Comment by OmTheTurtle** [comment]
This is also true for headings and paragraphs if both are selected (`.isActive("heading")` and `.isActive("paragraph")` will return false).

**Comment by bdbch** [comment]
I added this issue to our tracker and I will look into it!

**Comment by svenadlung** [comment]
Please keep in mind this is actually an expected behaviour. See docs:


> If your selection spans multiple nodes or marks, or only part of the selection has a mark, isActive() will return false and indicate nothing is active. This is how it is supposed to be, because it allows people to apply a new node or mark to that selection right-away.

https://tiptap.dev/guide/menus#the-active-state

In my opinion only moving cursor like @bdbch did here https://github.com/ueberdosis/tiptap/issues/2745#issuecomment-1166480491 is a misbehaviour.

**Comment by bdbch** [comment]
So I double checked this behavior again. Regarding @svenadlung it seems everything works as expected.

1. If you have a selection spanning a bold and italic element, both are inactive so you can add bold or italic respectively to the elements missing the mark.
2. If you have a bold text, a space and an italic text it makes sense to have everything inactive, since you can still make the non-bold text bold by clicking on it and vice versa for the italic text.
3. If we would have those buttons active, you'd first have to remove both styles and re-add both marks if you want to add marks to all of the selected content
4. Also if you move the arrow keys to move for example into a text with bold and italic marks, it makes sense to have both active, as you are currently not selecting but you're inserting content in between so you want both marks to be active for the new content.

The same also fits for the one @OmTheTurtle mentioned.
If you select a heading and a paragraph you sure can still click both, as you could apply the heading node to the paragraph or the paragraph to the headline node.

I also compared this behaviour to Google Docs and it seems to work the same there too.

I'll close this issue for now. If you think this really needs to be changed or you have another issue let me know.
