### ISSUE TITLE
Cursor hidden in Nodeview when <NodeViewContent> is wrapped in Flex in Chrome Browser

### ISSUE THREAD

**Issue by radialsolutions** [ueberdosis/tiptap#2773]
### What’s the bug you are facing?

I am creating a simple nodeview with React using the `<NodeViewContent> `helper component. This works as expected, until the `<NodeViewContent>` component is wrapped in a flexbox as below:

```
<div style={{ display: "flex" }}>
  <NodeViewContent className="content" />
</div>
```

at which point, the cursor is no longer shown when the block is empty. It is a similar result with `inline-block` or any display type other than the default `block`.

I can't seem to reproduce this in any other browser except chrome (version below)

### Which browser was this experienced in? Are any special extensions installed?

Chrome Version 101.0.4951.54 on M1 Macbook Pro 2021

### How can we reproduce the bug on our side?

1. Run the sandbox in Chrome browser
2. Notice that by default, the div wrapping the `<NodeViewContent>` is set to `display: flex` (I have added a button to simplifying toggling). 
3. The block should be shown without the cursor (when it is empty, when it has contents it behaves normally)
4. Click the button to toggle display to `display: block`
5. The block should be shown with the cursor as expected 

### Can you provide a CodeSandbox?

https://codesandbox.io/s/hopeful-stallman-ps9wjt

### What did you expect to happen?

I expected the cursor to remain, despite the content being wrapped in a flexbox

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @radialsolutions

The problem is that inside your `display: flex` container are a few other nodes (for example a div) that is not 100% width and has no content by default. This is normal behavior coming from flexbox which results in the div having a width of 0px. This is also why the cursor is not visible, since the element you're focused on is not really in view.

You can solve it by passing a className to the NodeViewContent (as you already did) and style it with CSS to have a full width.

What exactly are you trying to solve with the flex container by the way? Is it really necessary or are there other ways to solve the issue you're working on?

**Comment by radialsolutions** [comment]
Hey @bdbch thanks for this. I was just mainly confused why it was behaving differently in other browsers.

As for what I'm trying to do with the flex container - I am wrapping a bit of functionality around the contenteditable, kind of like a generalised notion block with draghandles/hover functionality etc. I mocked up the react component using flexboxes for the layout and planned to just wrap it around the contenteditable in the nodeview

**Comment by bdbch** [comment]
Ah I see. Did the `width: 100%` change fix your problem? I believe you can also give it a flex grow to cause it to take enough space.

**Comment by radialsolutions** [comment]
Nah I had to use `min-width: 100%;` but yeah flex grow is definitely a more _flex_ way to solve it. thanks again
