### ISSUE TITLE
Unable to run multiple unset commands

### ISSUE THREAD

**Issue by coderrahul** [ueberdosis/tiptap#2799]
### What’s the bug you are facing?

I have a scenario where I can set the text style to Bold, Italic, and Underline and I also want a rest option. When reset is clicked I am unset Bold, Italic, and Underline.

I have created a reset function and I am calling these three commands

```
editorState?.chain().focus().unsetUnderline().run();
editorState?.chain().focus().unsetItalic().run();
editorState?.chain().focus().unsetBold().run();
```

But after the first command is executed I am getting this error 

```
f90901e5-987f-4e5d-8a7d-279b214376bf:2 Uncaught RangeError: Applying a mismatched transaction
    at EditorState.applyInner (index.es.js?2bc4:863:34)
    at EditorState.applyTransaction (index.es.js?2bc4:831:1)
    at EditorState.apply (index.es.js?2bc4:807:1)
    at Editor.dispatchTransaction (tiptap-core.esm.js?747a:3449:1)
    at EditorView.dispatch (index.es.js?fc8a:5285:30)
    at Object.run (tiptap-core.esm.js?747a:1991:1)
```

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

Running these commands in a sequential order should result in the error

```
editorState?.chain().focus().unsetUnderline().run();
editorState?.chain().focus().unsetItalic().run();
editorState?.chain().focus().unsetBold().run();
```

### What did you expect to happen?

I want all these commands to execute without any exceptions

### Anything to add? (optional)

Is there already a better way to do this. I have tried

```
editor
  .chain()
  .focus()
  .unsetAllMarks()
  .run()
```

But I don't want any other things other than Bold, Italic and Underline to be removed for the selected text.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by codemzy** [comment]
This works for me...

```js
editor.chain().focus().unsetUnderline().unsetItalic().unsetBold().run()
```

As in, putting all the commands together in one chain rather than 3 separate chains.

**Comment by bdbch** [comment]
Hey @coderrahul, @codemzy's solution is exactly what you're looking for. The error `Applying a mismatched transaction` exactly tells you whats wrong. ProseMirror does changes via `transactions`. Simple said: It takes the current editors state and applies a set of changes to the state.

In your case, you take the same editor state and send 3 separate transactions to it via `.run()` which will break, because the state will be changed after the first transaction is completed and ProseMirror won't be able to merge the following transaction into it.

If something is wrong, let me know ✌️

**Comment by coderrahul** [comment]
Thanks a lot, @codemzy @bdbch. That's exactly what I am looking for 🎉
