### ISSUE TITLE
Block level markdown shortcuts removes previous mention nodes

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#2806]
### What’s the bug you are facing?

Imagine the following content: `[mentionNode] *|`, where `|` represents the text cursor. Pressing `<space>`, will transform the whole paragraph into a bullet list:

![firefox_8OQMmF1zHG](https://user-images.githubusercontent.com/96476/169362852-0d95c71f-9e54-456b-b58b-eda285df286b.gif)

### Which browser was this experienced in? Are any special extensions installed?

All of them. No, just `StarterKit` and `Mention`.

### How can we reproduce the bug on our side?

Follow the steps in the GIF above with CodeSandbox below.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-issue-2806-oef3p6

### What did you expect to happen?

Block level markdown shortcuts, like the bullet list, should be ignored if there's something like a mention preceding it.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖 _(on behalf of Doist)_

**Comment by bdbch** [comment]
Thanks, good find! Should be fixed asap 👍

**Comment by bdbch** [comment]
Looks great 👏

**Comment by bdbch** [comment]
Already found the culprit. Inside the InputRule we do a regex match on all the text before via `textBetween` and ignore spaces. Since for example mentions don't add any text, they are handled as spaces which results in the regex matcher to give a false positive.

I'll work on a fix for that now and will see how I can solve this issue without any big changes.

**Comment by rfgamaral** [comment]
When selecting a text fragment with a mention, and then copying that to the clipboard, the text version of the mention is copied, shouldn't the input rule be picking that up instead of "spaces"? 🤔

**Comment by bdbch** [comment]
I have a potential fix where I do a check inside the `wrappingInputRule` checking if there is a non-text node before the current position. If there is one - I abort the input rule.

It works but I'd rather fix that the inputRule is picking up mentions as normal text (as you already mentioned @rfgamaral) instead of doing a work around at a different position.

See this video:
https://user-images.githubusercontent.com/6538827/169398095-56e112c1-6f97-4a32-9c8e-7e5630552e71.mp4

Here you can see my fix is working but the mention is not added to the `textBefore` which was received via using `prose-model`'s `textBetween` method.

I'll take a look where the text gets lost so we can fix it without my wrappingInputRule fix. :)

**Comment by bdbch** [comment]
```
const textBefore = $from.parent.textBetween(
  Math.max(0, $from.parentOffset - maxMatch),
  $from.parentOffset,
  undefined,
  ' ',
) + text
```

It seems like this function is not respecting the content of non-text leaf nodes. The fourth argument allows us to define a placeholder for non-text leaf nodes which is currently `' '` resulting in a space being a replacement for the mention.

I'm not sure if we can just put some non-whitespace char here to make sure the regex is not returning a true because a non-text leaf node.

What are your thoughts @rfgamaral ?

**Comment by bdbch** [comment]
@rfgamaral I added a PR which would fix this a pragmatic way (adding a placeholder for non-text leaflets).

If you have feedback or further ideas let me know!

**Comment by rfgamaral** [comment]
I'll have some thoughts for you tomorrow. Thanks for digging deep into this issue 👍

**Comment by rfgamaral** [comment]
The `textBefore` seems to only be used for the input rule RegExp, so I guess it's okay to add a placeholder like that for all non-text leaflets? With that said, I'm sure you have more knowledge than myself about Tiptap/ProseMirror, so I trust your judgment.

However, I did look into a different solution, where the node text version is preserved, but a) this depends on nodes having a `renderText`, and b) this may be overengineering:

```diff
diff --git a/packages/core/src/InputRule.ts b/packages/core/src/InputRule.ts
index d147faff..c7fe54c2 100644
--- a/packages/core/src/InputRule.ts
+++ b/packages/core/src/InputRule.ts
@@ -115,19 +115,24 @@ function run(config: {
 
   let matched = false
   const maxMatch = 500
-  const textBefore = $from.parent.textBetween(
+  let textBefore = ''
+
+  $from.parent.nodesBetween(
     Math.max(0, $from.parentOffset - maxMatch),
     $from.parentOffset,
-    undefined,
-    ' ',
-  ) + text
+    (node, pos, parent, index) => {
+      textBefore += node.type.spec.toText?.({
+        node, pos, parent, index,
+      }) || node.textContent
+    },
+  )
 
   rules.forEach(rule => {
     if (matched) {
       return
     }
 
-    const match = inputRuleMatcherHandler(textBefore, rule.find)
+    const match = inputRuleMatcherHandler(textBefore + text, rule.find)
 
     if (!match) {
       return
```

**Comment by rfgamaral** [comment]
> I'll try something out with your solution to see if we can somehow combine it so nodes without a renderText function also get caught.

We could always do this: `|| node.textContent || '%leaf%'`.

**Comment by bdbch** [comment]
I updated my PR with your suggestion. Works fine! I actually like it more as the actual text content we receive is including the text from the nodes.
