### ISSUE TITLE
Input Node not working

### ISSUE THREAD

**Issue by joshuavachon25** [ueberdosis/tiptap#2913]
### What’s the bug you are facing?

I'm trying to create an Input node to insert in text to make a kind of text with holes where students have to fill the gaps. I tried the following code, but nothing appears in my editor when I run editor.chain().focus().setTrou({'data-x': trou}).run(). The idea is to put the good answer in data-x to then compare it with the answer from the student (easy to cheat, but those tests are formative, they don't count). 

When console.log(editor.chain().focus().setTrou({'data-x': trou}).run()), it returns false

### Which browser was this experienced in? Are any special extensions installed?

Chrome V.102.0.5005.115

### How can we reproduce the bug on our side?

```js
import {Node, mergeAttributes} from "@tiptap/core";

export const Trou = Node.create({
    name: 'trou',
    addOptions() {
        return {
            HTMLAttributes: {},
        }
    },
    addAttributes(){
        return {
            type: {
                default: "text",
            },
            'data-x': {
                default: ""
            },
            class: {
                default: "input input-xs input-bordered"
            }
        }
    },
    addCommands() {
        return {
            setTrou: (options) => ({ tr, commands }) => {
                if(tr.selection?.node?.type?.name == 'trou') {
                    return commands.updateAttributes('trou', options)
                }
                else {
                    return commands.insertContent({
                        type: this.name,
                        attrs: options
                    })
                }
            },
        }
    },
    parseHTML() {
        return [
            { tag: 'input' },
        ]
    },
    renderHTML({node, HTMLAttributes }) {
        return [
            'input',
            mergeAttributes(this.options.HTMLAttributes, HTMLAttributes)
        ]
    },
})
```

### What did you expect to happen?

Input field of type text with a attribute data-x and some Tailwind classes. But nothing appear.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @joshuavachon25

You have to add your group and inline information to your node so Prosemirror knows where and how to render it. Otherwise it will be rejected from the schema.

For example like that:

```js
inline: true,
group: "inline",
```

now there is another problem. Input elements are behaving quite weird in Prosemirror. Thats because it's conflicting with Prosemirror's focus and input handling.

You can see in this demo, that Prosemirror won't let you focus the input element in any way as it's trying to set a selection as soon as the focus falls inside the Prosemirror editor.

https://codesandbox.io/s/tiptap-input-elements-l435vw?file=/src/index.js

As you can see I have two examples implemented here - one by just using the renderHTML function to render an input element (which will behave weird because of the focus) and one using a ReactNodeView which works fine.

**BUT** playing around a bit with input elements in a prosemirror editor feels really weird. For example tabbing moves the focus all around the place and moving the selection inside a prosemirror editor into the node with an input field will now focus the input field but the wrapping node.

This may not be the best solution for your issue but at least your input element is rendered correctly this way.

If you need further information let me know!
