### ISSUE TITLE
`isTextSelection` always returns false

### ISSUE THREAD

**Issue by eduludi** [ueberdosis/tiptap#2979]
### What’s the bug you are facing?

The method `isTextSelection` always return `false` even when object is a `TextSelection`

### Which browser was this experienced in? Are any special extensions installed?

Chrome, Safari

### How can we reproduce the bug on our side?

1. Import `isTextSelection` from `@tiptap/core`

   ```js
   import { isTextSelection } from '@tiptap/core'
   ```

2. Provide `editor.state.selection` to it
   ```js
   const isTextSelected = isTextSelection(editor.state.selection)
   ```

3. Select a text and `isTextSelected` will be false

### Can you provide a CodeSandbox?

https://codesandbox.io/s/determined-gauss-7tnuji?file=/src/App.js

### What did you expect to happen?

`isTextSelected` should return `true` when text is selected

### Anything to add? (optional)

I'm using `@tiptap/react v2.0.0-beta.114` 
 
Thanks for this awesome library!

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by jorroll** [comment]
Just ran into this issue myself. `isNodeSelected()` also doesn't work. The problem seems to be that tiptap defines `isTextSelection` with:

```ts
function isTextSelection(value) {
    return isObject(value) && value instanceof TextSelection;
}

function isNodeSelection(value) {
    return isObject(value) && value instanceof NodeSelection;
}

function isObject(value) {
    return (value
        && typeof value === 'object'
        && !Array.isArray(value)
        && !isClass(value));
}

function isClass(value) {
    var _a;
    if (((_a = value.constructor) === null || _a === void 0 ? void 0 : _a.toString().substring(0, 5)) !== 'class') {
        return false;
    }
    return true;
}
```

It's not clear to me why tiptap's version of `isTextSelection` and `isNodeSelection` includes the `isObject()` check since it is unnecessary given the following `value instanceof TextSelection` check. More problematically though, `isObject()` includes the `!isClass()` call (Not sure why that is? I guess it's checking for just a POJO) and since `TextSelection` is a class instance `isClass()` is returning `true` resulting in `isObject()` returning `false`.
Solution:

```ts
function isTextSelection(value) {
    return value instanceof TextSelection;
}

function isNodeSelection(value) {
    return value instanceof NodeSelection;
}
```

**Comment by kivikakk** [comment]
It looks like ProseMirror's migration to TypeScript (which happened in 1.3.4->1.4.0) made this break since they weren't classes proper before then.

That update made its way into Tiptap in #2854, which was first released in `@tiptap/core@2.0.0-beta.180`, so likely broken since then.

**Comment by kivikakk** [comment]
PR opened at #3089.

**Comment by bdbch** [comment]
Great one @kivikakk - looking forward to merge your PR.
