### ISSUE TITLE
`keepOnSplit` is not working when node is split in between

### ISSUE THREAD

**Issue by jaulz** [ueberdosis/tiptap#3060]
### What’s the bug you are facing?

Maybe it's a misunderstanding but right now if I use `keepOnSplit` on a custom attribute and split a node in the middle, then the attribute is anyway copied to the second node.

### Which browser was this experienced in? Are any special extensions installed?

n/a

### How can we reproduce the bug on our side?

See following CodeSandbox link.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/mystifying-pond-ui144k?file=/src/App.vue

### What did you expect to happen?

I expected that the (new) second node will not have the same attribute as the first node.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by utdemir** [comment]
I can still reproduce this - do you think this is an issue, or if there's a workaround?

**Comment by Granipouss** [comment]
Up on that

Seems consistant with `keepOnSplit` for marks but counter intuitive and very much not handy.

From my understanding of the code is that 
-  `types` is `undefined` is the split is not at the end (https://github.com/ueberdosis/tiptap/blob/develop/packages/core/src/commands/splitBlock.ts#L72)
- We don't enter into the `if` that could set a value to `types` because `can` is `true` (https://github.com/ueberdosis/tiptap/blob/develop/packages/core/src/commands/splitBlock.ts#L85)
- So in the end the actual `split` is called with `types` being still `undefined` (https://github.com/ueberdosis/tiptap/blob/develop/packages/core/src/commands/splitBlock.ts#L100)
- And the ProseMirror behaviour for that is that, then we copy the current node and all it's properties (https://github.com/ProseMirror/prosemirror-transform/blob/e378fd30706ba3614f1f1a3b85d9954253d73cac/src/structure.ts#L183)

Honnestly I am not really familiar enough with tiptap and its philosophy to propose a fix, but there should be a place where `types` is given a proper value (with the Tiptap rules for attributes). I don't understand why we check for `!can` on line https://github.com/ueberdosis/tiptap/blob/develop/packages/core/src/commands/splitBlock.ts#L85. Naively I would have just dropped that condition, if there is no types and yet it is valid to had one, add it.

Hope it helps and I am willing to help more with the code if given instructions
