### ISSUE TITLE
How to Programmatically Apply a Style to any Given Range of Text (not just the range selected by the caret)

### ISSUE THREAD

**Issue by ANoobyBird** [ueberdosis/tiptap#3138]
### What problem are you facing?

I'm facing an issue where I cannot find a simple command to apply a style (or more generally, any modification) to a programmatically determined range of text at will (not just the text selected by the user) , save for the deletion `deleteRange` which is in the documentation. 

### What’s the solution you would like to see?

A method like `applyStyleToRange(style, range, mode)`, where `range` can be arbitrarily set by the programmer, would be much appreciated. If anything, one should be able to pick via a parameter `mode` roughly how forceful this application would be, for instance it could be forced to the entirety of the range specified, or it could be exerted upon only those which lack any style or formatting at the moment of the application, and so on.

### What alternatives did you consider?

No alternative has come to my mind yet. XD

### Anything to add? (optional)

Apart from the triviality, this feature is in fact almost all I need at the moment. Please excuse me if there is actually an easy or obvious way around this (and point out how to achieve it should you be so kind), I'm very new in programming and the frontend.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey! Since you can't just add styles in the middle of an HTML element, you'll need to use a Mark (for example we already have an existing TextStyle extension here: https://tiptap.dev/api/marks/text-style, but you can also write your own if you want to).

In theory, you then just need to set this mark via Tiptap/Prosemirror for a specific range. I don't think Tiptap does have an easy way to do this out of the box right now which I'll look into when I find time!
