### ISSUE TITLE
Custom variables

### ISSUE THREAD

**Issue by cnicodeme** [ueberdosis/tiptap#3175]
### What problem are you facing?

Hi,

I'm looking for a way to allow my users to have variables shown in the editor from a defined set. The idea is to write something like

"Hi {firstname|"there"}!"

And the editor would surround the {} code to a custom dom element with a style.
Clicking on it would allow the user to replace the "there" and would allow to write any other variables from a defined list ("name", "address", etc).

### What’s the solution you would like to see?

It's exactly what Intercom is offering, but generally speaking, something like this:

![image](https://user-images.githubusercontent.com/317142/189344100-6be0d56f-3c51-4cbc-b42b-81170497794d.png)

### What alternatives did you consider?

I'm not sure where to start. Maybe modifying one existing component, such as the "Mention" one, but I'm not sure here.
I'm hoping maybe someone has already done it or have a clear way onto what to do ?

Thanks :)

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @cnicodeme

Since this is not really a feature I'd close this issue and redirect you to either our [discussion board](https://github.com/ueberdosis/tiptap/discussions/categories/q-a) or our [Discord server](https://discord.gg/WtJ49jGshW) so the community can help you out with your questions.

In general it should be possible with an input rule and a custom node that handles the rendering of the tags and the logic.

**Comment by cnicodeme** [comment]
Sorry for the wrong place, I'll post it on the discussion board (didn't knew there was one ;) ). Thanks !
