### ISSUE TITLE
Unable to write text after inserting custom node

### ISSUE THREAD

**Issue by oferitz** [ueberdosis/tiptap#3176]
### What’s the bug you are facing?

I'm trying to achieve something similar to the [Dinos in the document example](https://prosemirror.net/examples/dino/) from ProseMirror examples.

I want to be able to write some text and then insert my custom node and write more text or add other elements but after I'm adding my custom node i'm unable to write any text afterwards in the same line. I just want my custom node to work like any other element exactly like in the Dino's example.  

### Which browser was this experienced in? Are any special extensions installed?

Chrome 105.0.5195.102

### How can we reproduce the bug on our side?

In the provided CodeSandbox Click on the "add dino" button and try to write some text.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/mystifying-roman-jenk7q?file=/src/App.tsx

### What did you expect to happen?

I expect the same functionality like in the ProseMirror Dinos example.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @oferitz

It seems like there is an issue with your DOM serialization. First thing I'd change is to remove the 0 in your marks `renderHTML` function.

so instead of 

```js
renderHTML({ HTMLAttributes }) {
  return [
    "img",
    mergeAttributes(this.options.HTMLAttributes, HTMLAttributes),
    0,
  ];
},
```

do

```js
renderHTML({ HTMLAttributes }) {
  return [
    "img",
    mergeAttributes(this.options.HTMLAttributes, HTMLAttributes)
  ];
},
```

otherwise ProseMirror will make a hole which is not correct as you actually have a correct DOM element here. (See https://prosemirror.net/docs/ref/#model.NodeSpec.toDOM)

Next you should also add a `toDOM` function like this:

```js
toDOM() {
  return ['img']
}
```

then it should work as expected. Can you verify that?

**Comment by oferitz** [comment]
@bdbch Thanks! I can verify that it is working as expected after refactoring per your suggestions.
