### ISSUE TITLE
Editor is being rendered with setTimeout (async)

### ISSUE THREAD

**Issue by ondrejsevcik** [ueberdosis/tiptap#3345]
### What’s the bug you are facing?

The Editor is being rendered asynchronously. Here on this line, the initialization is set after timeout (which makes it asynchronous). 

https://github.com/ueberdosis/tiptap/blob/4851fc5e9b6daccc15a1839e471db489401eca0c/packages/core/src/Editor.ts#L98

This makes it hard to use TipTap with other libraries that work with `clientHeight` (e.g. [react-window](https://github.com/bvaughn/react-window)).

### Which browser was this experienced in? Are any special extensions installed?

All browsers. 

### How can we reproduce the bug on our side?

Yes, please see attached codesandbox.

### Can you provide a CodeSandbox?

Here's a codesandbox demo demonstrating the problem - there is height calculated immediately after rendering and one after 1ms timeout. 

https://codesandbox.io/s/cranky-feather-9tf083?file=/src/App.js

### What did you expect to happen?

I would expect that TipTap is initialized and rendered synchronously.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by josephp27** [comment]
having this issue too. has there been a fix for this?

**Comment by bdbch** [comment]
Not yet.

Feel free to find a solution for this - I'll try to find some time to take a quick look into it next week but I don't think there will be a quick fix since I suspect Prosemirror rendering the content after processing the input and updating the state + view which will always delay the first render.

I'm not 100% sure how `react-window` works exactly, but can you look for resize changes via the `ResizeObserver` and let `react-window` know when the editor size changes?

What exactly changes with react-window when you enter a new line into your editor by the way? Wouldn't this cause errors since the height of the dom element would change after react-window calculates the virtualization heights?

**Comment by bdbch** [comment]
bump

**Comment by C-Hess** [comment]
I might try a crack at this. We're coming across the same issue with virtual scrolling libraries reliant on the height of the element being defined at mount if possible.

**Comment by ondrejsevcik** [comment]
This could be reopened. It is still relevant issue.

**Comment by kibertoad** [comment]
bump
