### ISSUE TITLE
Multiple cursors per user

### ISSUE THREAD

**Issue by avigoldman** [ueberdosis/tiptap#3370]
### What problem are you facing?

Hey folks,

I'm looking to provide the ability to insert multiple cursors for a single user similar to what Monaco supports.

### What’s the solution you would like to see?

I'd love to see an API to be able to insert a cursor and send all edits to all cursors tied to the user.

### What alternatives did you consider?

I'd thought about using the collaborative plugin and playing the edits through a "separate" user

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by ashu12chi** [comment]
Hi,
I think you can go through [this](https://github.com/ueberdosis/tiptap/discussions/1441) discussion.
@philippkuehn mentioned that they are not going to provide this feature: https://github.com/ueberdosis/tiptap/issues/1310

I am also interested in the same feature. It's good to know if there is any change of opinion with respect to [this](https://github.com/ueberdosis/tiptap/issues/1310#issuecomment-840025543) comment.

**Comment by bdbch** [comment]
We won't support this feature for now as @philippkuehn already explained Prosemirror doesn't support multiple cursors by default since Prosemirror uses the native text selection of the browser and a lot of the state handling is done by using the current cursors selection state.

What you can do as explained is to create `fake` selections that will reflect your multiple selections via decorations and update your changes you do in one place by rerunning the transaction for each "fake selection range".

But we can't support this feature right now. Thanks for requesting it though.
