### ISSUE TITLE
Toolbar i18n support

### ISSUE THREAD

**Issue by SalahAdDin** [ueberdosis/tiptap#3417]
### What problem are you facing?

Right now, we have a multi-language, while we can use the icon bar, it still displays banners in English, and we'd like it to display banners in the language the user is using their browser.

### What’s the solution you would like to see?

It should be like an API for overriding the plugins' literals, so we can override them as we require it

### What alternatives did you consider?

We don't consider any other solution, making a package for it would be a mess.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
Hi @SalahAdDin, can you please let me know what kind of banners (in English) you are referring to? Since Tiptap is "renderless" there shouldn't be any issue customizing any toolbar buttons.

**Comment by svenadlung** [comment]
@SalahAdDin I ask you to be more precise. Please create a CodeSandbox so we can understand the behavior. I am not sure where Tiptap prints text in toolbar or tooltip that is not set elsewhere by the developer. 

Since I can't see any wrongdoing on Tiptap's part so far, I'll close here. If it is still a bug, please let me know and I will reopen.
