### ISSUE TITLE
Pasting text wraps it in <code>

### ISSUE THREAD

**Issue by cyberalien** [ueberdosis/tiptap#3627]
### What’s the bug you are facing?

When trying to copy/paste text, sometimes editor treats it as code, sometimes as text, depending on where text was copied from.

### Which browser was this experienced in? Are any special extensions installed?

Chrome 108.0.5359.124
Safari 16.2

### How can we reproduce the bug on our side?

Can be reproduced in sample editor on https://tiptap.dev

Test sample to copy/paste: https://gist.githubusercontent.com/cyberalien/3bf1871bc10236acb5c09c394d8d5422/raw/86e228c5ab568161378ead7ffed3e6aa822906d1/test.txt

Steps to trigger bug:
1. Open sample Gist in browser, click "Raw" button to get raw text.
2. Select everything, copy to clipboard.
3. Open Tiptap website, select everything in editor, delete it, paste from clipboard.
4. Tiptap will wrap pasted text in `<code></code>`

Steps to trigger expected behaviour:
1. Download sample Gist file, open it in a simple text editor, such as TextEdit on macOS or Sublime Text.
2. Select everything, copy to clipboard.
3. Open Tiptap website, select everything in editor, delete it, paste from clipboard.
4. Tiptap will paste it the same way as if text was manually typed.

Screenshots to show difference in paste behaviour (first expected, then bug):
![tiptap-expected](https://user-images.githubusercontent.com/822287/212274428-d13441cf-51e9-438b-aaac-4e202e454ea4.png)
![tiptap-browser](https://user-images.githubusercontent.com/822287/212274434-3ae718b3-1f8b-44dc-bb32-b462f760f558.png)

### What did you expect to happen?

Expected text to be pasted the same way as if it was typed

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by zaidhaan** [comment]
This might possibly a feature, rather than a bug. Since clipboard store data in [multiple formats](https://stackoverflow.com/a/3571949), and what you get in your clipboard might vary from browser to browser.

I tried copying the content in that gist link on Firefox 110.0, and I can view the different mime types it gets stored in using the following command:
```sh
$ xclip -o -t TARGETS
TIMESTAMP
TARGETS
MULTIPLE
text/html
text/_moz_htmlcontext
text/_moz_htmlinfo
UTF8_STRING
COMPOUND_TEXT
TEXT
STRING
text/plain;charset=utf-8
text/plain
text/x-moz-url-priv
```

To view the plain text I could do the following
```sh
$ xclip -o -t text/plain
Inline code with link: `https://api.iconify.design/noto.css?icons=1st-place-medal,2nd-place-medal`

HTML block code:
...etc
```

If instead I were to do it using the `text/html` mime type I would get the following:
```
$ xclip -o -t text/html
<meta http-equiv="content-type" content="text/html; charset=utf-8"><pre>Inline code with link: `https://api.iconify.design/noto.css?icons=1st-place-medal,2nd-place-medal`

HTML block code:
...etc
</pre>
```
Notice the `<pre>` tag added in there? Well that's because _technically_ in that page, it's supposed to be showing you a raw text file but Firefox wraps it in a `<pre>` for you despite the raw response not including that. So when you copy that text, depending on your browser and how it displays the text, you might find an unexpected `<pre>` copied as a consequence of this.

So from the perspective of tiptap, it seems reasonable to display content that it seens enclosed in a `<pre>` tag as well, being in a code block.

**Comment by cyberalien** [comment]
Thanks for explanation. 

I think "Paste as plain text" would be very helpful here. Would it be possible to add that to popup menu?
