### ISSUE TITLE
Preserve Format on Paste

### ISSUE THREAD

**Issue by maertu** [ueberdosis/tiptap#3641]
### What problem are you facing?

When I copy content into tiptap a lot of formatting seems to get lost. f.e. if I copy a code block from an IDE like intellij, most wysiwyg editors like ckeditor, tinymce etc. are able to preserve the format, including Code highlighting background color etc. However, I was not able to accomplished with tiptap. I looked through all the Documentation and even the github issues but was not able to find any solution. 
I don't quite get if I am missing out something here, as I would expect this to work. I would really like to use TipTap as i find the API very intuitive, but I heavily rely on not losing formatting when copy content into tiptap. 

### What’s the solution you would like to see?

Easy way to be able to preserve content format when copying content into TipTap. 

### What alternatives did you consider?

Other editors like ckeditor or tinymce

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Deckluhm** [comment]
Tiptap preserves most common formatting (bold, italic, underline, tables, images... etc.) if you are using these extensions in your editor.

I regularly copy/paste Wikipedia articles into my Tiptap editor and most formatting is preserved (as intended).

Your issue looks like a misunderstanding of how Tiptap (and in general ProseMirror) works but it's hard to say since you didn't provided code. Can you please provide a repro?

**Comment by ashu12chi** [comment]
If you copy-paste code from VS-Code, then tiptap will be able to detect it as code and will convert it into the code-block with the correct language family. [Here](https://github.com/ueberdosis/tiptap/blob/8c6751f0c638effb22110b62b40a1632ea6867c9/packages/extension-code-block/src/code-block.ts#L238), they have added a VSCodeHandler which takes care of this thing, you can try out this by copying some content and pasting it in [this](https://tiptap.dev/api/nodes/code-block-lowlight#usage) example of tiptap. Here if the language is python then python styling will be applied which can be different from the source, but you can modify this by overriding the highlight.js CSS.
Coming to the point where certain editors show whatever you paste exactly the same with all styling, tiptap won't do that because it is based on a [strict schema](https://tiptap.dev/api/schema#introduction) which makes it always predictable and that is always better than showing what you have. (For some use cases this might be not good but for most use cases it is ideal) (**PS:** I can give you examples if you want more understanding here)
Rest, for copying from IntelliJ you can write a similar utility on your own.

**Comment by NitichaiSawangsai** [comment]
"@tiptap/extension-color": "2.0.0-beta.9",
    "@tiptap/extension-font-family": "2.0.0-beta.24",
    "@tiptap/extension-highlight": "2.0.0-beta.33",
    "@tiptap/extension-history": "2.0.0-beta.25",
    "@tiptap/extension-image": "2.0.0-beta.27",
    "@tiptap/extension-link": "2.0.0-beta.42",
    "@tiptap/extension-table": "2.0.0-beta.49",
    "@tiptap/extension-table-cell": "2.0.0-beta.20",
    "@tiptap/extension-table-header": "2.0.0-beta.25",
    "@tiptap/extension-table-row": "2.0.0-beta.22",
    "@tiptap/extension-task-item": "2.0.0-beta.32",
    "@tiptap/extension-task-list": "2.0.0-beta.26",
    "@tiptap/extension-text-align": "2.0.0-beta.31",
    "@tiptap/extension-text-style": "2.0.0-beta.26",
    "@tiptap/starter-kit": "2.0.0-beta.185",
    "@tiptap/vue-2": "2.0.0-beta.83",
    "tiptap-extensions": "^1.35.2",

I am encountering the same issue as mentioned in this thread, but I haven't found a solution yet. Can you help me?
