### ISSUE TITLE
how can i get the text that the node currently focus by the mouse

### ISSUE THREAD

**Issue by CedarXi** [ueberdosis/tiptap#3669]
### What’s the URL to the page you’re sending feedback for?

no

### What part of the documentation needs improvement?

![image](https://user-images.githubusercontent.com/16424854/215326780-781cfec2-37b5-47d4-aa89-0bdf2a615d0f.png)

### What is helpful about that part?

can't find in doc

### What is hard to understand, missing or misleading?

can't find in doc

**Comment by bdbch** [comment]
Not really an issue with the documentation so I'll close this issue.

What you could do to solve your problem is to use the current selection to get the node currently selected - get the offset of the cursor inside said node, subtract that from the current cursor position to find the node offset and then take this as the from position and the from position + nodeSize as the to position and then get the content from between those points.

Let me know if you need more help with this.
