### ISSUE TITLE
Inline components get recreated

### ISSUE THREAD

**Issue by jasonvarga** [ueberdosis/tiptap#372]
**Describe the bug**
Inline nodes with vue components get recreated whenever you hit enter in that paragraph.

**Steps to Reproduce / Codesandbox Example**
1. Go to https://codesandbox.io/s/vue-issue-template-6obkg
2. In a paragraph, click the `example` button to insert the node.
3. Check the console to see "node created" (from the `created` method in the vue component)
4. Hit enter in the paragraph somewhere before the node and see that "node created" is in the console.
5. Hit enter somewhere after, and it doesn't do it.

**Expected behavior**
The Vue component shouldn't be recreated.

**Comment by philippkuehn** [comment]
I think I can't do here anything but you can follow the discussion [here](https://discuss.prosemirror.net/t/prevent-full-re-render-of-node-views-within-paragraphs/2056).

**Comment by jasonvarga** [comment]
I had a feeling it might be a ProseMirror issue. Thanks for following up over there.

**Comment by philippkuehn** [comment]
@jasonvarga Ok, Marijn answered but I'm not sure how to implement such a caching system for now. What exactly is your problem with this bug? Do you show some animations on `mounted()` or is this a performance problem because you do some logic at `created()`?

**Comment by jackmcdade** [comment]
It's a performance problem because we have some components that need to perform AJAX requests, like images. Each time you edit the paragraph above an image, it re-requests the image and has a flash of unstyled content. I was hoping to not have to rewrite the integration to preload everything somehow, but if it can't be solved on the tiptap/prosemirror side, we can put it on the todo list.

**Comment by philippkuehn** [comment]
Yes, this is indeed a problem. Identifying a deleted node from the cache (what Marijn said) is a bit unclear to me, because in this case I can match a node only based on its attributes (?). And what happens to node views that doesn't need to be re-created? Should I delay every destroy of a node view? Surely you can't answer my questions, but these are my thoughts about it 🤔

**Comment by jackmcdade** [comment]
![Thinking...](https://thumbs.gfycat.com/SphericalRaggedFairyfly-size_restricted.gif)

**Comment by philippkuehn** [comment]
I created a caching system for components in a new branch (feature/node-view-cache) and it seems to be working fine when pressing enter. But components will be still re-created [when pressing backspace](https://discuss.prosemirror.net/t/prevent-full-re-render-of-node-views-within-paragraphs/2056/3?u=philippkuehn). 😩

**Comment by vitaliy-grusha** [comment]
I have same problem, but with block component. 
All components in document are recreated after moving cursor on some positions or after making a hard breaks.

It has strange behavior, sometimes recreation of components stops. 
After adding new nodes or components into document, recreation starts again.

**Comment by philippkuehn** [comment]
@vitaliy-grusha can you provide a codesandbox for this issue please?

**Comment by philippkuehn** [comment]
> I created a caching system for components in a new branch (feature/node-view-cache) and it seems to be working fine when pressing enter. But components will be still re-created when pressing backspace. 😩

I worked the last two days on a way to cache node views and it seems like I found a way to reuse node views in both of these cases. It’s not battletested yet but I think I can release this next week.

**Comment by jasonvarga** [comment]
Neat! Tiptap v2, I assume?

**Comment by philippkuehn** [comment]
yes 😬

**Comment by jasonvarga** [comment]
No problem! Happy you worked it out 🙂

**Comment by maxbaluev** [comment]
Any updates on this?
