### ISSUE TITLE
Vue component hierarchy does not match HTML tag hierarchy, thus making provide/inject useless in Vue

### ISSUE THREAD

**Issue by eta-orionis** [ueberdosis/tiptap#3758]
### What’s the bug you are facing?

I'm creating a custom node view whose content might include other custom nodes.

The generated HTML is properly nested 
```
<parent> 
   <child1 /> 
   <child2 /> 
</parent>
```

The Vue components, however, are all at the same level
```
<parent /> 
<child1 /> 
<child2 />
```

This broken hierarchy makes it impossible to use provide/inject between the parent and child components, and makes it difficult to reason about the behavior of the components. In combination with #3757, it makes it impossible to develop tabs, accordions, and other non-trivial node views.

### Which browser was this experienced in? Are any special extensions installed?

Safari, Chrome

### How can we reproduce the bug on our side?

Open the provided Sandbox and check the HTML source hierarchy and the Vue Component hierarchy.

Also: Notice how the message provided from the App level is passed without problems, whereas the message provided by the parent node is lost (notice in the console "injection "messageFromParent" not found")

### Can you provide a CodeSandbox?

https://codesandbox.io/s/divine-bush-itqofh?file=/src/App.vue

### What did you expect to happen?

I expected the Vue component hierarchy to match the HTML hierarchy and that provide/inject works normally.

### Anything to add? (optional)

Screenshot from Chrome DevTools, showing the two children being correctly inside their parent
![image](https://user-images.githubusercontent.com/3466670/219479560-6aa51791-e700-4260-9233-9fda6b0a1fa5.png)

Screenshot from Vue DevTools, showing all three node views (parent + 2 children) are at the same level in the Vue hierarchy
![image](https://user-images.githubusercontent.com/3466670/219479712-61f16fc1-b3e0-48e6-bf1e-9c40b3b88b51.png)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Tofandel** [comment]
Also have the same issue, it's quite important so it should probably be reopened

The way components are rendered may need to be revised, I'll see if I can make a PR

**Comment by sandstone991** [comment]
Having the same issue, Please consider reopening

**Comment by nperez0111** [comment]
> Having the same issue, Please consider reopening

What version are you on? We recently made a fix for this in a recent version within the past couple of weeks. Please upgrade to the latest and let me know if you still have issues

**Comment by Tofandel** [comment]
Just adding the PR that should normally solve this issue is https://github.com/ueberdosis/tiptap/pull/5373

**Comment by sandstone991** [comment]
> > Having the same issue, Please consider reopening
> 
> What version are you on? We recently made a fix for this in a recent version within the past couple of weeks. Please upgrade to the latest and let me know if you still have issues

I'm on 2.5.8

I haven't checked if component hierarchy still doesn't match the html because dev tools doesn't go below the EditorContent component for some reason. But I'm getting warnings that my injections were not found.

I'll try to give a codesandbox link with a minimal reproducible example if that helps.

**Comment by Tofandel** [comment]
I believe I looked into it and it was not a simple thing to fix, the problem stems from the fact that the rendering happens completely outside of vue in prosemirror. So the nodes are just rendered with `h` of vue (`createComponent`)  and then added to the dom manually but they are not actually in the component tree at all because this is happening outside the lifecycle of vue


We can manually tell `createComponent` the parent that renders the instance normally for provide inject to work, but this would require still knowing the component hierarchy, and because of prose mirror, this still happens linearly instead of in a tree
