### ISSUE TITLE
extension_table_1.default.configure is not a function

### ISSUE THREAD

**Issue by hilalbuyukgullu** [ueberdosis/tiptap#3771]
### What’s the bug you are facing?

I have a component library. There is no problem with the resizable table in this library. However, I am getting this error in projects where I have installed this library. This time when I remove the table config I get the textAlign config error

![image](https://user-images.githubusercontent.com/44446749/220377345-58ffe08d-8116-42ce-b3df-bb68aa35033b.png)

![image](https://user-images.githubusercontent.com/44446749/220377870-ed4d407f-f2ee-4c95-9c20-2e71379ba157.png)

![image](https://user-images.githubusercontent.com/44446749/220378013-501d71a3-35c5-4c1a-a19f-394bf7ba6301.png)

### Which browser was this experienced in? Are any special extensions installed?

I am getting the same error in all browsers.

### How can we reproduce the bug on our side?

I installed Tiptap in my own component library and it's ok. But when I add my own library in other projects I get an error

### Can you provide a CodeSandbox?

-

### What did you expect to happen?

I expected no errors.

### Anything to add? (optional)

-

### Did you update your dependencies?

- [x] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by dziraf** [comment]
I had a similar problem. You set dependencies to fixed versions, but `@tiptap` packages themselves specify their sibling dependencies versions with `^` prefix. Check if, for example, `node_modules/@tipta/starter-kit` has it's own `node_modules` and if it'd installed duplicate versions of your other packages such as `@tiptap/core` but higher versions than yours (ie `beta.220`).
If yes you can fix this by specifying `resolutions` in your `package.json`, this is mine:
```
  "resolutions": {
    "@tiptap/core": "2.0.0-beta.217",
    "@tiptap/extension-bubble-menu": "2.0.0-beta.217",
    "@tiptap/extension-character-count": "2.0.0-beta.217",
    "@tiptap/extension-code": "2.0.0-beta.217",
    "@tiptap/extension-document": "2.0.0-beta.217",
    "@tiptap/extension-floating-menu": "2.0.0-beta.217",
    "@tiptap/extension-heading": "2.0.0-beta.217",
    "@tiptap/extension-image": "2.0.0-beta.217",
    "@tiptap/extension-link": "2.0.0-beta.217",
    "@tiptap/extension-table": "2.0.0-beta.217",
    "@tiptap/extension-table-cell": "2.0.0-beta.217",
    "@tiptap/extension-table-header": "2.0.0-beta.217",
    "@tiptap/extension-table-row": "2.0.0-beta.217",
    "@tiptap/extension-text": "2.0.0-beta.217",
    "@tiptap/extension-text-align": "2.0.0-beta.217",
    "@tiptap/extension-typography": "2.0.0-beta.217",
    "@tiptap/pm": "2.0.0-beta.217",
    "@tiptap/react": "2.0.0-beta.217",
    "@tiptap/starter-kit": "2.0.0-beta.217"
  }
```
Also, if you're locking a version I suggest setting `resolutions` for all tiptap packages, even the ones you don't use yourself, since they're made to be compatible with matching versions and starter kit installs a lot of packages on it's own... This is quite messy but managable.

**Comment by robertu7** [comment]
Same issue and tried to lockdown the resolutions but doesn't work.

**Comment by walterdl** [comment]
Same error over here.

**Comment by yashug** [comment]
@hilalbuyukgullu you got any solution for this. i am also facing same issue when i create a component in my design system. i am using babel for build process and create react app setup

**Comment by james-bowers** [comment]
Same issue here

**Comment by nperez0111** [comment]
Is this still an issue? I think that named & default exports should work fine?
