### ISSUE TITLE
Google translate doesn't work with editor contents

### ISSUE THREAD

**Issue by thefinnomenon** [ueberdosis/tiptap#3826]
### What’s the bug you are facing?

When displaying editor content in read only mode, I want it to be translatable by google translate but it isn't due to ProseMirror setting `translate="no"` by default. I tried passing in yes to the editor's ProseMirror instance but it doesn't seem to be getting passed through.
```
editorProps: {
      attributes: {
        translate: "yes",
      },
    },
```

Relevant ProseMirror issue: https://github.com/ProseMirror/prosemirror/issues/1074

### Which browser was this experienced in? Are any special extensions installed?

Doesn't apply

### How can we reproduce the bug on our side?

Load editor & try to use google translate in Chrome to automatically translate the contents.

### What did you expect to happen?

The contents would be translated by Google translate

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by seeARMS** [comment]
We can check if `attr !== 'translate'` here: https://github.com/ProseMirror/prosemirror-view/blob/40ee2ef9882e352d7dde191f9e24fdeb8276cd88/src/index.js#LL390C7-L390C7

That would allow passing in `translate` as an `editorProp` directly to the view

**Comment by thefinnomenon** [comment]
Is there anyway we can bump the prosemirror-view version to 1.31.2 to fix this translation issue?

https://github.com/ProseMirror/prosemirror-view/releases/tag/1.31.2

**Comment by davidwessman** [comment]
Would need this too 🙂

**Comment by alexbowenAZ** [comment]
Would like this very much. Google translate is highly used by our users.

**Comment by heons** [comment]
The same here. We'd like to have this very much. 🙏

**Comment by ThisDavidRichard** [comment]
We are planning to release the new Editor update this week. We confirmed that the translation bug is fixed.

Review this [codesandbox](https://codesandbox.io/p/sandbox/eager-torvalds-d6thjl) featuring the rc8 which includes the fix. In this example, the editable state of the editor is set to false so that the editor does not persist the translated content.

I would advise to review the Editor & Translate behavior when the editable flag is set to true. This might introduce some unwanted UX behavior when not taken care of.
