### ISSUE TITLE
[Bug]: Spans are being removed from within p tags.

### ISSUE THREAD

**Issue by tmikaeld** [ueberdosis/tiptap#3921]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.0.1

### What’s the bug you are facing?

This should be valid:

`<p><span class="font-[300]">Super</span> <em>AI</em> E-commerce</p>`

### What browser are you using?

Chrome

### What did you expect to happen?

But it becomes this:

`<p>Super <em>AI</em> E-commerce</p>`

### Anything to add? (optional)

Having a span inside a p tag is fully valid HTML, please fix or advice how to allow it.

We're entering production soon, but this is blocking us entirely and we don't have the time to switch to a different editor.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by tmikaeld** [comment]
I modified our extension to also add a style tag, when we did that, the span isn't removed any more.

**Comment by svenadlung** [comment]
As @bdbch wrote, the behavior must be registered in the schema. Please check the docs, everything should be described there. Otherwise you can always ask in Discord for the correct approach.

Since I don't think this is a bug, I'll close here. If it is a bug, please let me know again, then I will open here again.
