### ISSUE TITLE
[Bug]: Floating menu does not seem to work in Vue 3 composition API

### ISSUE THREAD

**Issue by CarelessCourage** [ueberdosis/tiptap#3962]
### Which packages did you experience the bug in?

extension-floating-menu, vue

### What Tiptap version are you using?

2.0.2

### What’s the bug you are facing?

I'm just following the tiptap docs trying to implement a floating menu in vue 3 coomposition api. But the docs are in options API and when I convert it to composition API it breaks. In stackblitz it keeps giving me this error whenever I add the floating-menu `v-bind is missing expression.`

But in codesandbox and in my localhost it gives me this warning, and it doesnt render the floating menu. But If I switch to options API it works as expected. 
![image](https://user-images.githubusercontent.com/12764398/232197295-e1b97d10-21e1-4773-b746-c2749198b209.png)

[Stackblitz Composition API](https://stackblitz.com/edit/vue3-script-setup-with-vite-tedyxp?file=src%2FApp.vue,package.json)
[Codesandbox Composition API](https://codesandbox.io/p/sandbox/awesome-lederberg-854l0p?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A16%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A16%2C%22startLineNumber%22%3A6%7D%5D)
[Stackblitz Options API](https://stackblitz.com/edit/vue3-script-setup-with-vite-w9yqsy?file=src%2FApp.vue,src%2FEditor.vue)

[TipTap Floating Menu Docs](https://tiptap.dev/api/extensions/floating-menu)

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/p/sandbox/awesome-lederberg-854l0p?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A8%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A8%2C%22startLineNumber%22%3A16%7D%5D

### What did you expect to happen?

I expected the floating menu to work in composition api

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Mondotosz** [comment]
I don't have much experience with the library yet but I think that the issue comes from the fact that you are trying to use the extension as a component.

In the sandboxes you linked, you imported FloatingMenu from '@tiptap/extension-floating-menu' which is of type Extension when looking at the typescript definition.

[Here's the documentation section talking about using the extension with vanilla javascript](https://tiptap.dev/api/extensions/floating-menu#using-vanilla-java-script)

But here you are intending to use it with vue. In the [exemple from the documentation](https://tiptap.dev/api/extensions/floating-menu#using-a-framework), they don't import the extension and they don't register it when creating the editor but instead import it as a component like so `import { FloatingMenu } from '@tiptap/vue-3'`.

Here, FloatingMenu is of type DefineComponent and can be used in the template.

Hope this solves your issue.

**Comment by CarelessCourage** [comment]
@Mondotosz Aaaah, you're totally right. I missed the part where they imported floatingMenu from '@tiptap/vue-3' and not from the extention. Thank you so much. Closing the issue.
