### ISSUE TITLE
[Bug]: Cannot get editor.getAttributes('textAlign')

### ISSUE THREAD

**Issue by emewjin** [ueberdosis/tiptap#4240]
### Which packages did you experience the bug in?

text-align, core, react

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

Try to get current 'textAlign' value by `editor.getAttributes('textAlign')`, But cannot get value. It just return empty object.

```js
  console.log(
    editor.getAttributes("textAlign"),
    editor.getAttributes("alignments"),
    editor.getAttributes("align"),
    editor.getAttributes("textStyle"),
    editor.getAttributes("alignment"),
    editor.getAttributes("textAlignment"),
    editor.getAttributes("text-align")
  ); 
// {} {} {} {} {} {} {}
```

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/p/sandbox/recursing-roman-yhxqqn?file=%2Fsrc%2FApp.tsx%3A65%2C2

### What did you expect to happen?

```js
// after run {textAlign: center}
console.log(editor.getAttributes("textAlign")) // 'center'

// after run {textAlign: left}
console.log(editor.getAttributes("textAlign")) // 'left'

// after run {textAlign: right}
console.log(editor.getAttributes("textAlign")) // 'right'
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by kongweiying2** [comment]
I'm having this issue too.

**Comment by bdbch** [comment]
The problem is the usage of the `getAttributes` function. `getAttributes` requires a node or mark name as it's argument, not an attribute name.

If you want to get the attributes of the attribute your anchor is in you can do the following:

```js
editor.getAttributes(editor.state.selection.$anchor.node().type.name)
```

It should return `{ textAlign: 'center' }` for example

**Comment by sjdemartini** [comment]
I had a similar question as OP and appreciated the suggestion to use `editor.state.selection.$anchor.node().type.name`! However, that seems to not work properly in all scenarios. For instance, when an `Image` is selected, that "current node name" snippet returns `'doc'` (rather than `'image'` as expected) and so `editor.getAttributes('doc')` returns `{}` regardless of the `textAlign` that is set. 

To reproduce:
1. Insert an image
2. Change its alignment to center
3. Confirm `editor.isActive({textAlign:'center'})` === `true` as expected
4. Notice that `editor.getAttributes(editor.state.selection.$anchor.node().type.name)` returns `{}` instead of `{ textAlign: 'center' }`

**Comment by sjdemartini** [comment]
For what it's worth, for text-align in particular I've been using [this](https://github.com/sjdemartini/mui-tiptap/blob/6562cf24b6096fee478bbea84e4dc99ea8372407/src/controls/MenuSelectTextAlign.tsx#L155-L158) sort of workaround in [mui-tiptap](https://github.com/sjdemartini/mui-tiptap), since there are only four possible values so we can exhaustively check them:

```ts
const currentAlignment = ["left", "center", "right", "justify"].find((alignment) =>
  editor.isActive({ textAlign: alignment })
);
```

A more straightforward/general single-method approach would be nice and probably more performant though.
