### ISSUE TITLE
[Bug]: this.editor is undefined in `addAttributes`

### ISSUE THREAD

**Issue by piszczu4** [ueberdosis/tiptap#4421]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

`editor` in `addAttributes()` method is always `undefined`. I have an extension and inside `addAttributes()` I defined the following logic:

```
	addAttributes() {
		let { editor } = this;
		return {
			revealed: {
				default: false,
				renderHTML: (attributes) => {
					return {
						class:
							"spoiler" +
							(attributes.revealed && editor?.isEditable ? " is-visible" : ""),
						"data-spoiler": _t("nodes.spoiler_reveal_text"),
					};
				},
			},
		};
	},
```

Unfortunately `editor` is undefined and hence I can't use `isEditable` prop. I think that the solution would be to update `getAttributesFromExtensions()` method and pass `editor` there. 

### What browser are you using?

Chrome

### What did you expect to happen?

`editor` not being undefined

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by edymusajev** [comment]
Still an issue.

**Comment by nperez0111** [comment]
addAttributes cannot always have the editor instance, because in order to make the editor instance, it needs the attributes to create the schema to create the editor instance.

In your case, you should not be using the editor.isEditable prop anyway, because changing the schema just because an option was provided is not advised, if you want to do that you can use an option via a configure or addOptions method.

Or you can juse use CSS since all this is doing is a conditional classname.
