### ISSUE TITLE
[Bug]: Can't set attribute for element

### ISSUE THREAD

**Issue by shilpa9608** [ueberdosis/tiptap#4457]
### Which packages did you experience the bug in?

Tiptap with react

### What Tiptap version are you using?

2.0.0-beta.113

### What’s the bug you are facing?

**### In Javascript**  we can set attribute like this , 
var myElement = document.getElementById("myElementId");

// Set the attribute
myElement.setAttribute("attributeName", "attributeValue");

We would like to know, how to set an attribute for an element using tiptap . Is there any code available to do the same thing  mentioned above, using tiptap.

### What browser are you using?

Chrome

### What did you expect to happen?

If we set the attribute using JavaScript it will remove after refresh by Tiptap extension . So we need to add or update an attribute value for an element created using an custom extension .

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by shilpa9608** [comment]
Is there any solution to resolve this problem??

**Comment by Renjith-SB** [comment]
We are also facing this issue, give solution for that

**Comment by bdbch** [comment]
You need to add attributes to the Prosemirror schema - otherwise Prosemirror will strip out any attribute that is not allowed.

There are 2 ways:

1. Add your wanted attribute on an extension level (for example if only the paragraph should have said attribute, extend the `Paragraph` extension and add attributes via `addAttributes`. (see https://tiptap.dev/guide/custom-extensions#attributes)
2. You can add attributes on a global level for multiple nodes via global attributes. (see https://tiptap.dev/guide/custom-extensions#global-attributes)

After that just use the `updateAttribute` command on your node/mark.
