### ISSUE TITLE
[Bug]: textAlign justify implementation is flawed

### ISSUE THREAD

**Issue by sujan-s** [ueberdosis/tiptap#4715]
### Which packages did you experience the bug in?

textAlign

### What Tiptap version are you using?

2.1.13

### What’s the bug you are facing?

Currently, text align can be set to one of: ['left', 'center', 'right', 'justify'].

Technically, the justify option should be in addition to text align values. You should be able to set left-justify, center-justify etc to a node.

This is easily achieved with:
```
text-align      : justify;
text-align-last : left | center | right;
```

This justifies the block, and aligns the last line as preferred, as is the case with all typesetting tools.

### What browser are you using?

Chrome

### What did you expect to happen?

To have the ability to justify and align the last line as needed.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by dcourv** [comment]
I just checked, and it looks like word processors like Pages and Google Docs only have the exclusive left-align, center-align, right-align, and justify options. I’m curious, what is your use case for this feature?

I’m not a tiptap dev, but it seems like this level of specificity might be a better candidate for a custom extension rather than integration into the built-in extension.

**Comment by sujan-s** [comment]
@dcourv TextAlign is already a Tiptap extension: https://tiptap.dev/docs/editor/api/extensions/text-align

I’m trying to build a typesetting tool that works in the browser, so this is crucial IMHO. Currently I’m doing this in a hacky way by setting style attributes, and I’m having to use both Tiptap text-align options and my implementation working in parallel.

I’m hoping to do this cleanly, hence raised this issue.

**Comment by codemzy** [comment]
I'd agree with @dcourv that this probably isn't a bug since most word processors (and wysiwyg editors) only have left, right, center and justify options.

> Technically, the justify option should be in addition to text align values.

Justify is a text-align value https://developer.mozilla.org/en-US/docs/Web/CSS/text-align so I think the current implementation is correct.

The `text-align-last` aligns the last line of text, it could be used with `text-align: center;` or `text-align: left;` so it's not really `text-align` but could be added as an extra option for your use case (extend TextAlign or recreate it as a custom extension with the extra option). You could then decide to only add the `text-align-last` style if `text-align` is justify.

Something like:

```js
if (attributes.textAlign === "justify") {
  return { style: `text-align: justify; text-align-last: ${attributes.textAlignLast}` }
}
```

**Comment by sujan-s** [comment]
Fair enough—maybe not a bug—but definitely room for improvement. 

I still stand by my opinion—`justify` should be boolean, and left/centre/right should be available on top of that.

@codemzy I am currently doing that conditional manually anyway—but might be worthwhile to add to Tiptap. I only suggest that because Tiptap seems to have lofty goals, and aims to be better than a casual text editor. Thoughts?

**Comment by dcourv** [comment]
Would you like to share your code for doing it manually? I agree it could be a cool feature and useful for some.

**Comment by sujan-s** [comment]
```
export interface EditorPreferences {
    fontFamily  : "Inter" | "IBM Plex Serif" | "IBM Plex Mono";
    fontSize    : number,
    lineHeight  : number,
    textAlign   : "left" | "center" | "right";
    isJustified : boolean;
}


const editorPreferences = user!.editorPreferences;

const editorStyles = useMemo(() => {
    return {
        fontFamily: `${editorPreferences.fontFamily}`,
        fontSize: `${editorPreferences.fontSize}px`,
        lineHeight: editorPreferences.lineHeight,
        textAlign: editorPreferences.isJustified ? "justify" : `${editorPreferences.textAlign} `,
        textAlignLast: editorPreferences.isJustified ? `${editorPreferences.textAlign}` : undefined,
    };
}, [ editorPreferences ]);
```

@dcourv Here you go. Justify is a checkbox, and then you can apply the left/centre/right alignment independently.

**Comment by codemzy** [comment]
I like your implementation and how it works for what you need. 

But it's not how I would want TextAlign to work for my use-case - because I think my users would get confused if they had text center aligned, and then changed text-align to justified, and the last line stayed center aligned. Just because that's not how most text editors work.

And what if I wanted to justify the last line with `text-align-last: justify;`? 

Or something whacky, like I wanted to center the text with `text-align: center;` and then have `text-align-last: right;`? Not something I would want to do but is possible with `text-align-last` and shown in the MDN example here: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align-last

Just my thoughts, but since it's going beyond the standard text-align css class (which is the style TextAlign applies), I do think this is a custom extension use case.

You could extend TextAlign `const CustomTextAlign = TextAlign.extend({` to add the extra option, like you are currently doing but within your own [custom textAlign extension](https://tiptap.dev/docs/editor/guide/custom-extensions#extend-existing-extensions). Because it seems like you would just need two extra options, since I think the last line is justified left by default with justify (I may be wrong here!) you can just add a 'justify-center' and a 'justify-right' alignment?

If you look at the [source code](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-text-align/src/text-align.ts), you could add some extra options like:

```js
import TextAlign from '@tiptap/extension-text-align';

// custom text align extension 
const CustomTextAlign = TextAlign.extend({

  addOptions() {
    return {
      types: [],
      alignments: ['left', 'center', 'right', 'justify', 'justify-center', 'justify-right'], // two extra custom options
      defaultAlignment: 'left',
    }
  },

  addGlobalAttributes() {
    return [
      {
        types: this.options.types,
        attributes: {
          textAlign: {
            default: this.options.defaultAlignment,
            parseHTML: element => element.style.textAlign || this.options.defaultAlignment,
            renderHTML: attributes => {
              if (attributes.textAlign === this.options.defaultAlignment) {
                return {}
              }
              if (attributes.textAlign.includes('justify-')) { // handle the custom options
                return { style: `text-align: justify; text-align-last: ${attributes.textAlign.replace("justify-", "")}` }
              }
              return { style: `text-align: ${attributes.textAlign}` }
            },
          },
        },
      },
    ]
  },

});
```

I've not tested the above but I think it would get you close.

Or keep it the way you have it if it works better for your use case!

I think that's the great thing about tiptap and how you can customise extensions to add your own options and features that might not be the "norm" but create something unique!

**Comment by sujan-s** [comment]
Ok, makes sense.

Guess it’s a trade-off between catering to everyday users vs advanced use cases.

I’ve attached a video showing the interface and experience I’m going for—

https://github.com/ueberdosis/tiptap/assets/19920532/8f42b015-70b0-4dde-8b99-03e5e39467f5

Note how the icons change when justification is turned on/off. 

This way, I could avoid six congested icons on the UI. And, in typesetting, it’s incredibly unlikely to have a left-aligned+right-aligned-last combo—which you can achieve with two separate blocks anyway.

But, since the extension can be extended like you demonstrated, I’m happy with that.
