### ISSUE TITLE
[Bug]: Jest unit test fails for useEditor()

### ISSUE THREAD

**Issue by ClaudiuGS** [ueberdosis/tiptap#5108]
### Which packages did you experience the bug in?

    "@tiptap/core": "^2.3.0",     "@tiptap/extension-bold": "^2.3.0,  "react": "^18.2.0",",     "@tiptap/extension-document": "^2.3.0",     "@tiptap/extension-hard-break": "^2.3.0",     "@tiptap/extension-history": "^2.3.0",     "@tiptap/extension-paragraph": "^2.3.0",     "@tiptap/extension-strike": "^2.3.0",     "@tiptap/extension-text": "^2.3.0",     "@tiptap/pm": "^2.3.0",     "@tiptap/react": "^2.3.0",

### What Tiptap version are you using?

2.3.0

### What’s the bug you are facing?

I've upgraded TipTap from 2.1.13 to 2.3.0 and now my unit tests are failing. After inspection, it seems that useEditor always returns `null`.

I've tried commenting out all my custom code and using a very basic example of Editor but useEditor still returns `null`.

### What browser are you using?

Chrome

### What did you expect to happen?

Expected my unit tests not to fail as in previous version.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by nnuzaba** [comment]
I am also seeing this issue.

Pretty sure it was due to this change in 2.3.1: https://github.com/ueberdosis/tiptap/pull/4856

Specifically [removal of this line](https://github.com/ueberdosis/tiptap/pull/4856/files#diff-13acb5e551812e195c1140c10ba5ac298a0005996d07756cfd77c2d4194cb350L103) 

Before that the setEditor was updating state and causing a rerender, and then returning a not null editor.

(I tried copy pasting the old version of the code with the setEditor and my tests start working again)

As a workaround, I'm doing a rerender using React testing library's 'rerender' for now, but it is very hacky 😢 

@svenadlung if you could explain why this is not an issue in the production code, it would help us understand what we need to emulate in our tests.

**Comment by nperez0111** [comment]
SSR is the reason behind this. Without a document the editor can fail since it is expected to run within the browser. With the new react binding and `immediatelyRender: true` you can control this behavior in tiptap 2.5

But do note that any bugs that happen on the server are not going to be prioritized as the editor is not meant to be ran there and could have incompatibilities

**Comment by nnuzaba** [comment]
Sorry confused, but our tests were running with jest-dom, so wouldn't that mean it did have a "browser", and was not doing SSR? (our team can't upgrade React so we can't use the new stuff 😅 )

**Comment by nperez0111** [comment]
My comment around SSR was the reason why we changed `useEditor` to return null on first render & then an actual editor instance afterward (via a useEffect which would not be called in SSR).

jest-dom emulates a browser, but is not an actual instance, I'm unsure if it can even declare a global document instance or not, in any case tiptap is not really meant to be running in a node instance.
