### ISSUE TITLE
[Bug]: BubbleMenu and Collaboration Extension conflict in 2.3.2

### ISSUE THREAD

**Issue by chenyuncai** [ueberdosis/tiptap#5131]
### Which packages did you experience the bug in?

core vue3 document paragrapg text extension-collaboration

### What Tiptap version are you using?

2.3.2

### What’s the bug you are facing?

 Case: Upgrade all extension and core packages from 2.3.1 to 2.3.2
    Problem: BubbleMenu didnot works, applying mismatched transaction .... and stops me to edit anything
    Useful Info: 

      1. downgrade y-prosemirror to 1.2.3 works fine.
      2. remove Collaboration Extension and works fine too.

    It seems the two packages confict in new version 2.3.2

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/p/devbox/nuxt-tiptap-nn5zp7

### What did you expect to happen?

The BubbleMenu component should works as before and no error edit message in console

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by itzaks** [comment]
I've been seeing the same bug coming up the latest week, fixed it by removing the use of `FloatingMenu` from `@tiptap/vue-3`

**Comment by beocaca** [comment]
> FloatingMenu

how to do that sir

**Comment by zxqp** [comment]
Facing the same issue, any update?

currently downgrading "y-prosemirror" to "1.2.3" works, but not sure if it will affect the collaboration.

`error "@tiptap/extension-collaboration#y-prosemirror@^1.2.5" doesn't satisfy found match of "y-prosemirror@1.2.3"`

`error "@tiptap/extension-collaboration-cursor#y-prosemirror@^1.2.5" doesn't satisfy found match of "y-prosemirror@1.2.3"`

**Comment by neaumusic** [comment]
having a similar issue, we do have collab though I've disabled it for local dev. using create-react-app 5 and StarterKit 2.4.0

something about 'insertNode' on something that isnt a child:

[bubble-menu-hot-reload-stack-trace.txt](https://github.com/user-attachments/files/15971381/bubble-menu-hot-reload-stack-trace.txt)

**Comment by zxqp** [comment]
I'm still experiencing the issue. Is there any update on a fix?

**Comment by michaeldeprospo** [comment]
I'm still experiencing this issue with Vue3.

**Comment by nperez0111** [comment]
You will need to update y-prosemirror version, there was a bug with it

Just to be safe, update all tiptap packages & y-prosemirror if you have it explicitly declared in your pjson

**Comment by zxqp** [comment]
BubbleMenu is positioned incorrectly after updating all tiptap packages and y-prosemirror to ^1.2.11. The menu is always displayed at the top of the editor, regardless of the cursor's position.

Steps to Reproduce:
Update all tiptap packages to their latest versions.
Upgrade y-prosemirror to a version higher than 1.2.3.
Open an editor and attempt to use the BubbleMenu.

Expected Behavior:
The BubbleMenu should appear at the cursor's position when the user clicks on a word or selection.

Actual Behavior:
The BubbleMenu is consistently shown at the top of the editor, regardless of the cursor's location.

Additional Notes:
If y-prosemirror is kept at version 1.2.3 while updating other tiptap packages, the BubbleMenu functions correctly.
