### ISSUE TITLE
[Bug]: Editor is not actually read when onCreate is called

### ISSUE THREAD

**Issue by Nantris** [ueberdosis/tiptap#5237]
### Affected Packages

react? or otherwise core

### Version(s)

2.5.0-beta.3 and below

### Bug Description

The editor cannot be focused when `onCreate` is called because the editor DOM element is not yet attached to the page's DOM.

This occurs even if you wait until an animation frame has passed. In CodeSandbox it seems that two animation frames are sufficient to access the editor's DOM on the page, but in my project that's not the case and instead it takes three, so it seems like there might be two components to this issue.

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/dark-worker-tjp86f?file=%2Fsrc%2FApp.js%3A19%2C35

### Expected Behavior

I'd suggest a `ready` event, which occurs after the `create` event that means the editor is fully ready. Short of that, I'd think that `create` means I can access the editor to do whatever I need, especially based on the description.

### Additional Context (Optional)

The `create` event is described as "The editor is ready." That's arguably true because the headless editor is ready, but it's arguably not, because some real world uses aren't possible at that time.

**Regarding the repro** you have to click into the frame for the focus command to actually work, so I'd recommend:

1. Click refresh
2. Very quickly click into the frame
3. The frame refreshed
4. If the `focus` command worked, the editor will now have a caret shortly after refresh

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
I'm pretty sure this is to do with the react integration, because the first render pass it is not actually attached to any dom element. I hope to fix this with https://github.com/ueberdosis/tiptap/pull/5161 but we are still reviewing it.

<img width="1893" alt="image" src="https://github.com/ueberdosis/tiptap/assets/1852538/f8385a53-bf62-4b11-8b44-d86a3ec117aa">

But a way around this is to use a useEffect like I've done here: https://codesandbox.io/p/sandbox/dark-worker-tjp86f?file=%2Fsrc%2FApp.js%3A19%2C35

screen shot since I don't trust that I've linked that properly: 
<img width="889" alt="image" src="https://github.com/ueberdosis/tiptap/assets/1852538/1708d6a0-ea9d-4a54-8b17-aa4682fa4b70">


But, in any case the autofocusing should work. But if you have the y-prosemirror extension we are seeing it not work, but it is a y-prosemirror issue not a tiptap one. See that thread here: https://github.com/ueberdosis/tiptap/issues/2840#issuecomment-2174320269

Hope this helps

**Comment by Nantris** [comment]
@nperez0111 despite the fantastic work on #5161, I still find we need a triple `requestAnimationFrame` inside of `onCreate`. We don't use `y-prosemirror`

**Comment by Nantris** [comment]
@nperez0111 despite the fantastic work on #5161, I still find we need a triple `requestAnimationFrame` inside of `onCreate`. We don't use `y-prosemirror`

This is proving to be quite a problem for us because users expect their selection to be persisted across documents as it did with our old editor, but the requirement for 3x `requestAnimationFrame` introduces over 50ms of delay.
