### ISSUE TITLE
[Bug]: CharacterCount extension counts wrong Tiptap instance

### ISSUE THREAD

**Issue by vonWolfehaus** [ueberdosis/tiptap#5295]
### Affected Packages

core, CharacterCount

### Version(s)

2.4.0

### Bug Description

If there are multiple Tiptap editor instances, only the latest editor to be added to the DOM will be counted correctly. The previous instances will only reflect the count (character and word) of the latest editor.

Please visit the github repo, clone it, and then run `yarn && yarn dev` to launch the local server.

Repro steps: 
- click the "Add Editor" button.
- type in the new instance and take note of the word count.
- focus back on the first editor instance and notice that the word count now matches the word count of the new editor instance.
- now type in the first instance. Notice the word count does not change.
- focus and type in the second instance. Notice how the word count changes for both instances.

### Browser Used

Chrome

### Code Example URL

https://github.com/vonWolfehaus/tiptap-char-count-bug

### Expected Behavior

The word count for all editor instances should only reflect the count for the instance it belongs to.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Yea, I actually recently discovered this in this issue too: https://github.com/ueberdosis/tiptap/issues/4664

The quick fix should be the same there (a dummy `.extend` where you are rendering the component). I am going to close this one as a dupe since it is actually better explained in this issue: https://github.com/ueberdosis/tiptap/issues/4664
