### ISSUE TITLE
Apply toggleHeaderRow always to the first row of a table

### ISSUE THREAD

**Issue by Sakessonholm** [ueberdosis/tiptap#548]
**Is your feature request related to a problem? Please describe.**
I want to be able to toggle the first row of a table to be a header row or not. The current implementation seems to be that you can toggle the _currently selected_ row/column/cell as a header.

**Describe the solution you'd like**
I want my users to be able to create a table and then choose to "enable a header row" which should be the first row of the table. For that I need a command to toggle the header row and it shouldn't matter which row I'm currently in. If they click it once it sets the first row as a header row, if they click it again it makes the first row a normal row again.

**Describe alternatives you've considered**
The current commands only toggles the _currently selected_ row/column/cell as a header.

**Additional context**
In my opinion this is a quite common behaviour of a lot of editors dealing with tables, to be able to decide if the top row is a header row or not.

**Comment by Sakessonholm** [comment]
I'm still trying to understand how plugins work with TipTap and ProseMirror, and I _think_ this could be achieved by a plugin that finds the first row of a table and then runs the _**toggleHeaderRow**_ command on it. If my assumption is correct I would appreciate any help on how such a plugin would look.

**Comment by Duncank** [comment]
I'm using v2 and am looking for something like this as well. In my case, knowing if the selected cell is on the first row would suffice.

**Comment by philippkuehn** [comment]
Thanks for these code snippets. Closing it for now.

**Comment by philippkuehn** [comment]
This has been fixed in #2412 🎉

**Comment by codemzy** [comment]
Nice work on #2412 - could I ask if `toggleHeaderCell` will remain with its current functionality? Being able to turn any cell in a table into a `th`, rather than just first row or first column. I believe that that is [valid html](https://validator.w3.org/#validate_by_input). The pull request asks for feedback, so I just wanted to mention that is useful to have, as I'm using this feature in the editor, to get table layouts like this...

![Screenshot 2022-01-26 at 11 23 47](https://user-images.githubusercontent.com/13764272/151154942-83fd0c98-95f2-4bb7-8fd8-c5baf445c04d.png)

**Comment by philippkuehn** [comment]
@codemzy `toggleHeaderCell` is still available 👍
