### ISSUE TITLE
[Bug]: Colgroup missing in JSON when using getJSON

### ISSUE THREAD

**Issue by liltechnomancer** [ueberdosis/tiptap#5498]
### Affected Packages

extension-table

### Version(s)

2.6.3

### Bug Description

When using editor.getHTML() there is a colgroup used for resizing the columns. This is not present in the JSON returned from  editor.getJson()

### Browser Used

Chrome

### Expected Behavior

I would expect there to be some sort of JSON object for colgroups. 

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
The colgroup element is derived from the JSON: https://github.com/ueberdosis/tiptap/blob/ce141c2e69ddc47c29658b9a6ad4ee16607774bb/packages/extension-table/src/table.ts#L279-L291

Can you explain your usecase, why would you need it available in the JSON?

**Comment by liltechnomancer** [comment]
Hey thanks so much for the quick reply. 

I am using TipTap as an editor for HTML emails via the library Vue Email. 

Currently I use a modified version of Gutentap, which is mostly a modified starter kit. 
I then take the json and use a recursive function to turn it into Vue components. 

Since email supports tables the transformation for them is just `h('tag')`. 

It would be ideal to have access to the colgroup info so I can do the same with it.

**Comment by nperez0111** [comment]
Forgive me for my ignorance here. But my understanding would be that colgroup wouldn't really be necessary for your case since we already set the width on each table cell individually?

I'm just trying to help you at at this point, I don't think that there is any way to get that information into the JSON, it is explicitly tied to table cell widths and there is not a great way to communicate changes across different extensions (it would have to be implemented as it's own node type to actually show in the JSON since that is what the JSON is ultimately trying to represent).


If it is really necessary for your case, then I'm going to have to say that it is on you to implement that. I'd be willing to take a PR if it does not add too much complexity to how tables are implemented but I think that is just not really possible given what it does

**Comment by liltechnomancer** [comment]
If anyone stumbles across this with the same issue, colwidth is an array, so it can't be passed straight to `h("td")` this is what made me miss it entirely. This can easily be fixed with a real component as the wrapper.
