### ISSUE TITLE
[Bug]: `:marker` pseudo-element color not applied in numbered and bullet list

### ISSUE THREAD

**Issue by bbonczek** [ueberdosis/tiptap#5525]
### Affected Packages

core

### Version(s)

2.3.0

### Bug Description

The `:marker` pseudo-element is not inheriting or applying the specified color in numbered and bullet lists. You can see it in tiptap demo page as well.
1. Add bullet / numbered list.
2. Apply color to it

I'd expect marker to be colored as well. Instead it's black.

### Browser Used

Chrome

### Expected Behavior

I'd expect marker to be colored as well.

### Additional Context (Optional)

[cinnamon-2024-08-20T120419+0200.webm](https://github.com/user-attachments/assets/cab4748a-21f6-4a24-8da4-b06a44c5253c)

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
The marks apply to the text within the paragraph, not the list itself. To apply it to more types you'd have to configure the extension to apply to listItem's I guess: https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/extension-color/src/color.ts#L4-L12

I don't think we'd want to do this on our editor, since unfortunately there are bugs with applying marks to nodes when being synced with yjs (our collaboration backend)
