### ISSUE TITLE
[Bug]: insertContent does not preserve marks on inserted TextNodes

### ISSUE THREAD

**Issue by Nantris** [ueberdosis/tiptap#5540]
### Affected Packages

core

### Version(s)

2.5.6

### Bug Description

We're trying to slice part of the document and re-insert it to preserve marks but I find `insertContent` loses those marks.

### Browser Used

Chrome

### Expected Behavior

Inserted ProseMirror nodes preserve marks as is currently possible when feeding `insertContent` an HTML string.

### Additional Context (Optional)

This occurs whether you try to insert one node or multiple nodes.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by Nantris** [comment]
**Example of input:** 
![image](https://github.com/user-attachments/assets/49131e69-23c7-4fc5-b1dd-b865a5258a59)

In these cases `createNodeFromContent` returns an empty array.

I'm starting to think I have an incorrect expectation about the command's capabilities. In any event I can presumably handle this at the ProseMirror level, but it would be nice if it could be done with a single call to `insertContent`.

**Comment by nperez0111** [comment]
insertContent is for HTML or JSON content not Prosemirror nodes. This is reflected in its types. I do not think we should be adding prosemirror nodes because if they are generated from another schema they will not be valid in this schema. This leads to complexity that makes it easy to do the wrong thing. 

Literally all you would need to do is to do Fragment.from(contentYouAreInserting).toJSON() and insertContent with that.

**Comment by Nantris** [comment]
> `Fragment.from(contentYouAreInserting).toJSON()`

Ended up just doing a `.command(({tr}) => tr.insert(...)}` but that's nifty! Thanks for the tip!

Studying the underlying types might indeed have made it more clear, but in the IDE it just says it accepts, `value: Content` which isn't super clear on the surface.
