### ISSUE TITLE
[Bug]: During initialization, multiple consecutive spaces entered into the editor will be merged into one space

### ISSUE THREAD

**Issue by machiming** [ueberdosis/tiptap#5541]
### Affected Packages

vue

### Version(s)

2.0.4

### Bug Description

During initialization, multiple consecutive spaces entering the editor will be merged into one space. How can we display multiple spaces correctly

### Browser Used

Chrome

### Expected Behavior

 During initialization, multiple consecutive spaces entering the editor will be merged into one space. How can we display multiple spaces correctly

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
https://tiptap.dev/docs/editor/api/editor#parseoptions

The editor by default respects HTML rules where whitespace is removed, to preserve whitespace you need to tell the editor to preserve it.

Normally I would only recommend doing this on a per-node basis rather than the whole editor, but to each their own
