### ISSUE TITLE
[Bug]: Codeblock removes "tagged" users

### ISSUE THREAD

**Issue by kart-c** [ueberdosis/tiptap#5609]
### Affected Packages

@tiptap/extension-mention, @tiptap/extension-code-block

### Version(s)

2.6.6

### Bug Description

Adding a codeblock removes the mentioned user. I have also tried cloning the repository and the same issue can be reproduced in the `demos\src\Nodes\Mention\React\index.jsx` project (by adding the Codeblock extension.)

Steps to reproduce - 
1. Tag a user
2. Add codeblock to that particular line. The tagged user is removed
3. Removing the codeblock removes the mention as well

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/magical-meitner-zwlpq3

https://github.com/user-attachments/assets/9bf1dad3-9ab1-4087-ac0d-735dadfe6e75

### Expected Behavior

Codeblock should not remove the mention text.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
A code block only accepts text as its content. A mention is implemented as an inline node so it is removed when converting between the paragraph which allows that kind of content into a code block. So this is expected behavior.

**Comment by kart-c** [comment]
Hey @nperez0111 is there a reason why code only accepts `text` and not `inline*` as its content?
If I were to use code on a tagged user in either discord or slack it works as expected which is why I raised it as an issue.


https://github.com/user-attachments/assets/4b7af39a-da61-4c84-8d0b-21307049424a

**Comment by nperez0111** [comment]
> Hey @nperez0111 is there a reason why code only accepts `text` and not `inline*` as its content? If I were to use codeblock on a tagged user in either discord or slack it works as expected which is why I raised it as an issue.

There definitely is a reason why it only accepts text, code is edited slightly differently than normal text (e.g. newlines are meaningful), and it does not make sense to be able allow things like formatting on code (e.g. what does it mean to bold a for loop).

There could probably be a more graceful way of trying to preserve the mention text. I wonder if it could just use the renderText method to "downlevel" to text. But atm I'm unsure how that would actually work since this is up to prosemirror in how it chooses to "fit" content.

I hope this answers your question.

**Comment by kart-c** [comment]
Thanks @nperez0111 for the explanation.

**Comment by vuld-2609** [comment]
same issue
