### ISSUE TITLE
[Bug]: setTextAlign in ListItem，dot or index cannot follow

### ISSUE THREAD

**Issue by ZhaoJianXXXXX** [ueberdosis/tiptap#5713]
### Affected Packages

extension-bullet-list/extension-order-list

### Version(s)

both 2.8.0

### Bug Description

setTextAlign('left')
1.111
2.222
3.333

setTextAlign('center')
1.                  111
2.                  222
3.                 333

setTextAlign('center')
1.                                          111
2.                                         222
3.                                        333

### Browser Used

Chrome

### Code Example URL

https://templates.tiptap.dev/QMGRPczTJd

### Expected Behavior

Just look at the position of the head directly

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by ZhaoJianXXXXX** [comment]
last one is setTextAlign('right')

**Comment by bdbch** [comment]
This one is expected as text align **should** only align text. Those list decorators are not part of normal text content. One solution would be to set the ::marker on list items to `list-style-position: inside` and set the paragraph inside a `li` to inline-block / or let the list item flex.

But still the issue is the text-align only being set on the paragraph.
