### ISSUE TITLE
How do we capture the events emitted from custom vue components in the editor component?

### ISSUE THREAD

**Issue by kshitizshankar** [ueberdosis/tiptap#620]
Hey 

How do we listen for the events emitted from custom vue component extensions?

```
<editor-content
  :editor="editor"
  class="editor__content"
  @myevent="myEventHandler"
/>
```
This doesn't seem to work.

The editor contains an extension that uses a Vue component which emits `"myevent"`.

Feels like I am missing a middle step here.

Thanks!

**Comment by jgabis** [comment]
Hey, I had the same problem and here is what I did:

In the mark-component, instead of
` this.$emit('myevent') `
I used
` this.$parent.$emit('myevent')`
 and then
 `<editor-content
  :editor="editor"
  class="editor__content"
  @myevent="myEventHandler"
/>`
should work. This way the editor-content emits this event and we can listen for it in editor wrapper. Hope it helps.

**Comment by kshitizshankar** [comment]
@jgabis Ohh - didn't think about that. Thanks! 

I ended up passing a callback as an option to the extension, which is then invoked from the custom views. Not sure if I'll run into issues with it later or not - but for now, it solved my immediate use-case.
