### ISSUE TITLE
Selection changed only on second click

### ISSUE THREAD

**Issue by mc-martin-o** [ueberdosis/tiptap#648]
When I use the Focus-Plugin and if the current focus is outside the editor you have to click twice to change the cursor position. This only happens in Firefox but not in Chrome.

I could reproduce the behaviour with the focus example on https://tiptap.scrumpy.io/focus
- if you load the page the editor has focus and the selection is at the beginning of the text
- then click outside the editor so it looses the focus
- when you then click at a new position the editor regains focus and the old selection is restored but should change to the position where I clicked
- a second click eventually changes the selection as expected

**Comment by Julien1138** [comment]
The decoration function of the Plugin's props is actually called twice in a row when the editor was not focused. But if the first call does not return a proper DecorationSet like it currently does, the second call never occurs and the cursor is not positioned.

The workaround I found works only because I don't apply any CSS using the `has-focus` class. I use it to position a floating menu for tables.
If you do use this workaround to display an actual decoration, it will be shown even if the editor is not in focus. And if you use the 
`ProseMirror-focused` class like I tried, it will blink to the last position before actualizing correctly.

I wrote a custom Focus class removing the test about the editor being focused or active:
```js
import { Extension, Plugin } from 'tiptap'
import { DecorationSet, Decoration } from 'prosemirror-view'

export default class Focus extends Extension {

  get name() {
    return 'focus'
  }

  get defaultOptions() {
    return {
      className: 'has-focus',
      nested: false,
    }
  }

  get plugins() {
    return [
      new Plugin({
        props: {
          decorations: ({ doc, selection }) => {
            const { anchor } = selection
            const decorations = []

            doc.descendants((node, pos) => {
              const hasAnchor = anchor >= pos && anchor <= (pos + node.nodeSize)

              if (hasAnchor && !node.isText) {
                const decoration = Decoration.node(pos, pos + node.nodeSize, {
                  class: this.options.className,
                })
                decorations.push(decoration)
              }

              return this.options.nested
            })

            return DecorationSet.create(doc, decorations)
          },
        },
      }),
    ]
  }

}
```

I hope it helps.
