### ISSUE TITLE
Question - Do I have to install scss loader to use TodoList?

### ISSUE THREAD

**Issue by rob-sullivan** [ueberdosis/tiptap#746]
Do I have to install scss loader to use TodoList?
Code here: https://github.com/scrumpy/tiptap/tree/master/examples/Components/Routes/TodoList

**Comment by durub** [comment]
You don't have to. You could convert the Sass styles to CSS using an online converter (e.g. https://jsonformatter.org/scss-to-css).

1. Replace the `@import "~variables";` with the [file contents](https://github.com/scrumpy/tiptap/blob/master/examples/assets/sass/variables.scss)
2. Convert
3. Use the generated CSS instead of the SCSS
