### ISSUE TITLE
Pasting doesn't allow commas in pasted url

### ISSUE THREAD

**Issue by joshward** [ueberdosis/tiptap#824]
**Describe the bug**
Pasting a valid url like `https://tiptap.dev?abc=xyz,test` auto links only up to the comma even though the whole pasted value is a valid url.

**Steps to Reproduce / Codesandbox Example**
1. Paste a valid url with a comma in it into the editor e.g. `https://tiptap.dev?abc=xyz,test`
2. Tiptap creates a link that doesn't include the comma and beyond

**Expected behavior**
Expect the entire valid url with the comma to be auto linked

**Screenshots**
After pasting:
![image](https://user-images.githubusercontent.com/11366954/92127190-e8decb00-edb5-11ea-8a12-81dbeb48072e.png)

**Environment**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 1.29.4
 - Mobile / Desktop: Tested on desktop

**Comment by aquelehugo** [comment]
I am still having this issue with 

```
"@tiptap/core": "2.0.0-beta.85",
"@tiptap/extension-link": "^2.0.0-beta.20",
"@tiptap/react": "^2.0.0-beta.82"
```

The demo at https://tiptap.dev/api/marks/link works though. Any clue?

**Comment by aquelehugo** [comment]
@philippkuehn sorry. My issue is with semicolons right now, the issue with commas is fixed, but we have some real urls using semicolons.
Should I open another issue?

**Comment by philippkuehn** [comment]
@aquelehugo yes, please. we are using linkify for url detection, so I think we can’t do here anything. but let’s see.

**Comment by aquelehugo** [comment]
@philippkuehn We were using Preact and for performance reasons we are migrating back to React, because of React 18 improvements.
A teammate was suspicious about Preact being the culprit on this issue and it was.
I had issues with Preact compatibility with other input-related libraries in the past, so I guess it is not worth it handling that.
Thank you for the amazing work and support and sorry for flooding here :grimacing:
