### ISSUE TITLE
tiptap-utils@1.11.0 run error

### ISSUE THREAD

**Issue by windyoung1990** [ueberdosis/tiptap#837]
![image](https://user-images.githubusercontent.com/21021859/93470247-2ef26d80-f924-11ea-8d16-b2e0150bea3d.png)
![image](https://user-images.githubusercontent.com/21021859/93470328-50535980-f924-11ea-9db4-2bf691bb6ac5.png)

**Comment by hanspagel** [comment]
Would you mind to add a little bit of context to your screenshots?

**Comment by windyoung1990** [comment]
> Would you mind to add a little bit of context to your screenshots?

what kindof message would you want to get?

**Comment by hanspagel** [comment]
We mentioned the most important things in the issue template. Adding more info here helps us to fix the issues and helps to get people searching for the issue here. ✌️

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to Reproduce / Codesandbox Example**
Steps to reproduce the behavior:
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See error

Fork this or create a new Codesandbox replicating your error
https://codesandbox.io/s/vue-issue-template-h0g28

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
 - Mobile / Desktop: [eg. Desktop]

**Additional context**
Add any other context about the problem here.

**Comment by windyoung1990** [comment]
> We mentioned the most important things in the issue template. Adding more info here helps us to fix the issues and helps to get people searching for the issue here. ✌️
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **Steps to Reproduce / Codesandbox Example**
> Steps to reproduce the behavior:
> 
> 1. Go to '…'
> 2. Click on '…'
> 3. Scroll down to '…'
> 4. See error
> 
> Fork this or create a new Codesandbox replicating your error
> https://codesandbox.io/s/vue-issue-template-h0g28
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Environment**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> * Mobile / Desktop: [eg. Desktop]
> 
> **Additional context**
> Add any other context about the problem here.

It could be a little difficult for me.The error occurs in program building stage.Now I solve it by fixed version in npm-shrinkwrap.json so that tiptap-utils is not the lastest version.If nobody others has this problem, you can close this issue.Thanks!

**Comment by hanspagel** [comment]
Thanks for sharing!
