### ISSUE TITLE
Replacing nbsp; to regular spaces

### ISSUE THREAD

**Issue by Krutie** [ueberdosis/tiptap#943]
**Bug Description**
 `&nbsp;` won't convert into regular spaces even after using `parseOptions : { preserveWhitespace: true | false }`
 
Issue #754 already discusses this, but the proposed solution in PR #254 doesn't quite solve the problem. Below is the reproduction steps.

**Expected behaviour**
When copy/pasting the content, the editor should cleanup all the `&nbsp;`s. Manually writing the content doesn't create unwanted `&nbsp;`s.

Steps to reproduce the behaviour:
1. Copy the content below (It has plenty of `&nbsp;` in it.):
It is one of the refined sins of civilisation, for we know not what wild spirit we are taking from its purer atmosphere, or who it is?
2. Paste the content from Step 1 into Tiptap Editor at https://8igbl.csb.app/
3. See all the `&nbsp;`s in the Chrome Dev Tools
**Screenshot**
![Chrome Dev Tool](https://nuxt-diagrams-temp.s3-ap-southeast-2.amazonaws.com/tiptap.png)

**Codesandbox replicating the issue**
https://codesandbox.io/s/friendly-thompson-8igbl?file=/src/App.vue

**Comment by domnantas** [comment]
@hanspagel Hey, was this fixed? I'm trying to get rid of `&nbsp;` on pasted text, https://github.com/ueberdosis/tiptap/issues/754 points to `parseOptions`, but `parseOptions.preserveWhitespace` doesn't seem to have any impact in this case.

**Comment by domnantas** [comment]
Solved the issue by adding
```js
new Editor({
	editorProps: {
		transformPastedText(text) {
			return text.replace(/\xA0/g, " ");
		},
		transformPastedHTML(html) {
			return html.replace(/\xA0/g, " ");
		},
	},
})
```

This [docs part](https://tiptap.dev/guide/custom-extensions/#access-the-prosemirror-api) mentions
> To hook into events, for example a click, double click or when content is pasted, you can pass event handlers as editorProps to the editor.

but it's a bit unclear – `addProseMirrorPlugins` example below causes confusion, there's no link to [editor props docs](https://tiptap.dev/api/editor#editor-props) (and they only show `attributes.class` changed). Should I submit an update for the docs?

**Comment by chrisdellisantirn** [comment]
To add to this I was confused as to why `replace(/\xA0/g, " ");` worked to remove `&nbsp;` in the transformPastedHTML function only some of the times. It's because when pasting from various sources the characters may be formatted differently but show up in the DOM as the browser interprets the characters. So the answer is that `\xA0` is the Unicode format for it will remove `&nbsp`. 

I'm currently working on cleaning up cleaning up content pasted from MS Word and I found `.replace(/\u200B/g, "")` to handle cleaning up `&ZeroWidthSpace;` well.
